namespace ZodSharp.SourceGenerators;

partial class ZodSchemaGeneratorTests
{
	[Test]
	public async Task Generate_GivenModel_GeneratedSchemaHasExpectedStructure(CancellationToken cancellationToken)
	{
		// Arrange
		const string source =
			@"
namespace Testing
{
	[ZodSchema]
	public class Customer
	{
		public string? Name { get; set; }
	}
}
";

		// Act
		var (result, outputCompilation) = await GenerateAsync(source, cancellationToken);
		var generatedSource = GetSchemaGeneratedSource(result, "CustomerSchema");

		// Assert
		await AssertNoGeneratorExceptions(result);
		await AssertNoCompilationErrors(outputCompilation, cancellationToken);
		await Assert.That(generatedSource).StartsWith("// <auto-generated />");
		await Assert.That(generatedSource).Contains("namespace Testing;");
		await Assert.That(generatedSource).Contains("#nullable enable");
		await Assert.That(generatedSource).Contains("public static partial class CustomerSchema");
		await Assert.That(generatedSource).Contains("GeneratedCodeAttribute");
		await Assert.That(generatedSource).Contains("CompilerGenerated");
		await Assert.That(generatedSource).Contains("ExcludeFromCodeCoverageAttribute");
	}

	[Test]
	public async Task Generate_GivenClassWithoutZodSchema_DoesNotGenerateSchema(CancellationToken cancellationToken)
	{
		// Arrange
		const string source =
			@"
namespace Testing
{
	public class Customer { }
}
";

		// Act
		var (result, outputCompilation) = await GenerateAsync(source, cancellationToken);
		var generatedSource = GetSchemaGeneratedSource(result, "CustomerSchema");

		// Assert
		await AssertNoGeneratorExceptions(result);
		await AssertNoCompilationErrors(outputCompilation, cancellationToken);
		await Assert.That(generatedSource).IsEmpty();
	}

	[Test]
	public async Task Generate_GivenMultipleAnnotatedTypes_GeneratesAllSchemas(CancellationToken cancellationToken)
	{
		// Arrange
		const string source =
			@"
namespace Testing
{
	[ZodSchema]
	public class Customer { }

	[ZodSchema]
	public struct Address { }

	[ZodSchema]
	public record Order { }
}
";

		// Act
		var (result, outputCompilation) = await GenerateAsync(source, cancellationToken);

		// Assert
		await AssertNoGeneratorExceptions(result);
		await AssertNoCompilationErrors(outputCompilation, cancellationToken);
		await Assert.That(GetSchemaGeneratedSource(result, "CustomerSchema")).IsNotEmpty();
		await Assert.That(GetSchemaGeneratedSource(result, "AddressSchema")).IsNotEmpty();
		await Assert.That(GetSchemaGeneratedSource(result, "OrderSchema")).IsNotEmpty();
	}
}
