using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace ZodSharp.Json;

/// <summary>
/// Cross-platform tests: C# (Newtonsoft.Json) $lt;--$gt; TS (Zod).
///
/// These tests:
/// 1. Read JSON fixtures generated by the TS/Zod side.
/// 2. Deserialize and validate them with ZodSharp + Newtonsoft.Json.
/// 3. Check that validation outcomes match the TS manifest.
/// 4. Write validated data back as C# output JSON for the TS side to consume.
/// </summary>
public class NewtonsoftCrossPlatformTests
{
	static readonly JsonSerializerSettings CamelCaseSettings = new()
	{
		ContractResolver = new CamelCasePropertyNamesContractResolver(),
	};

	static readonly System.Text.Json.JsonSerializerOptions ManifestOptions = new()
	{
		PropertyNameCaseInsensitive = true,
	};

	static readonly string FixturesDir = Path.Combine("..", "..", "..", "..", "..", "..", "src", "ts", "fixtures");
	static readonly string OutputDir = Path.Combine(
		"..",
		"..",
		"..",
		"..",
		"..",
		"..",
		"src",
		"tests",
		"cross-platform",
		"output"
	);
	static readonly string ManifestPath = Path.Combine(FixturesDir, "manifest.json");

	static readonly string[] InvalidKeys =
	[
		"invalidEmptyName",
		"invalidNegativeAge",
		"invalidOverMaxAge",
		"invalidBadEmail",
		"invalidMissingName",
	];
	static readonly string[] ValidKeys = ["valid", "validMinimal", "validMaxAge"];

	/// <summary>
	/// Loads the TS-generated manifest that records which fixtures should be valid/invalid.
	/// </summary>
	static CrossPlatformManifest LoadManifest()
	{
		var json = File.ReadAllText(ManifestPath);
		return System.Text.Json.JsonSerializer.Deserialize<CrossPlatformManifest>(json, ManifestOptions)!;
	}

	/// <summary>
	/// Reads all fixture JSON files from the TS fixtures directory.
	/// </summary>
	static IEnumerable<(string Name, string Json)> LoadAllFixtures()
	{
		foreach (var file in Directory.GetFiles(FixturesDir, "*.json"))
		{
			var name = Path.GetFileNameWithoutExtension(file);
			if (name == "manifest")
				continue;
			yield return (name, File.ReadAllText(file));
		}
	}

	[Test]
	[MethodDataSource(nameof(ValidFixtureNames))]
	public async Task Newtonsoft_CanDeserializeAndValidate_ValidFixtureFromTS(string fixtureName)
	{
		var json = File.ReadAllText(Path.Combine(FixturesDir, $"{fixtureName}.json"));
		CrossPlatformUserSchema schema = new();

		var result = schema.DeserializeAndValidate(json);

		await Assert.That(result.IsSuccess).IsTrue();
		await Assert.That(result.Value!.Name).IsNotNull();
		await Assert.That(result.Value!.Name!.Length).IsGreaterThanOrEqualTo(1);
		await Assert.That(result.Value!.Age).IsGreaterThanOrEqualTo(0);
		await Assert.That(result.Value!.Age).IsLessThanOrEqualTo(120);
	}

	[Test]
	[MethodDataSource(nameof(InvalidFixtureNames))]
	public async Task Newtonsoft_Rejects_InvalidFixtureFromTS(string fixtureName)
	{
		var json = File.ReadAllText(Path.Combine(FixturesDir, $"{fixtureName}.json"));
		CrossPlatformUserSchema schema = new();

		var result = schema.DeserializeAndValidate(json);

		await Assert.That(result.IsSuccess).IsFalse();
	}

	[Test]
	public async Task Newtonsoft_ValidationOutcomes_MatchTSManifest()
	{
		var manifest = LoadManifest();

		foreach (var (name, json) in LoadAllFixtures())
		{
			CrossPlatformUserSchema schema = new();
			var result = schema.DeserializeAndValidate(json);
			var expectedValid = manifest[name].Valid;

			await Assert
				.That(result.IsSuccess)
				.IsEqualTo(expectedValid)
				.Because(
					$"fixture '{name}': C# result ({result.IsSuccess}) should match TS manifest ({expectedValid})"
				);
		}
	}

	[Test]
	public async Task Newtonsoft_SerializesValidData_CanBeParsedByTS_Zod(CancellationToken cancellationToken)
	{
		// Serialize valid data using Newtonsoft with camelCase, write to output dir for TS tests to consume
		CrossPlatformUserSchema schema = new();
		CrossPlatformUser user = new()
		{
			Name = "CSharp Export",
			Age = 42,
			Email = "csharp@example.com",
			Tags = ["newtonsoft", "export"],
		};

		var result = schema.ValidateAndSerialize(user, CamelCaseSettings);
		await Assert.That(result.IsSuccess).IsTrue();

		Directory.CreateDirectory(OutputDir);
		var outputPath = Path.Combine(OutputDir, "newtonsoft-valid.json");
		await File.WriteAllTextAsync(outputPath, result.Value, cancellationToken);

		// Verify the output is valid JSON with expected fields
		var writtenJson = await File.ReadAllTextAsync(outputPath, cancellationToken);
		await Assert.That(writtenJson).Contains("CSharp Export");
		await Assert.That(writtenJson).Contains("42");
		await Assert.That(writtenJson).Contains("csharp@example.com");
	}

	[Test]
	public async Task Newtonsoft_RoundTrip_TSFixture_ToCSharp_ToJSON_BackToCSharp(CancellationToken cancellationToken)
	{
		// Read TS fixture -> deserialize in C# -> re-serialize in C# -> re-deserialize in C#
		var originalJson = await File.ReadAllTextAsync(Path.Combine(FixturesDir, "valid.json"), cancellationToken);
		CrossPlatformUserSchema schema = new();

		var firstResult = schema.DeserializeAndValidate(originalJson);
		await Assert.That(firstResult.IsSuccess).IsTrue();

		var serializeResult = schema.ValidateAndSerialize(firstResult.Value!, CamelCaseSettings);
		await Assert.That(serializeResult.IsSuccess).IsTrue();

		var secondResult = schema.DeserializeAndValidate(serializeResult.Value!);
		await Assert.That(secondResult.IsSuccess).IsTrue();
		await Assert.That(secondResult.Value!.Name).IsEqualTo(firstResult.Value!.Name);
		await Assert.That(secondResult.Value!.Age).IsEqualTo(firstResult.Value!.Age);
	}

	public static IEnumerable<string> ValidFixtureNames() => ValidKeys;

	public static IEnumerable<string> InvalidFixtureNames() => InvalidKeys;
}
