<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Purview.ZodSharp.AspNetCore.UnitTests</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Examples.CLI\Examples.CLI.csproj" />
		<ProjectReference Include="..\..\src\AspNetCore\AspNetCore.csproj" />
		<ProjectReference Include="..\..\src\ZodSharp\ZodSharp.csproj" />
	</ItemGroup>

	<ItemGroup>
		<!-- Runs the generator against the test project.
         This makes generated attributes/types available to test source code. -->
		<ProjectReference
			Include="..\..\src\SourceGenerators\SourceGenerators.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
			PrivateAssets="all"
		/>
	</ItemGroup>
</Project>
