using System.Collections.Immutable;
using ZodSharp.AspNetCore.SourceGenerators.Helpers;
using ZodSharp.AspNetCore.SourceGenerators.Models;

namespace ZodSharp.AspNetCore.SourceGenerators;

partial class ErrorTypeGenerator
{
	static void Emit(CodeWriter writer, ErrorTypeFieldModel model)
	{
		var parameterNames = BuildParameterNames(model.Parameters);
		var parameters = BuildMethodParameters(parameterNames, writer);

		writer
			.AutoGeneratedHeader()
			.Using("System.Collections.Generic")
			.Using("ZodSharp.AspNetCore")
			.Using("ZodSharp.Core")
			.NewLine();

		using (writer.BlockNamespaceScope(model.Namespace))
		{
			using (
				writer.ClassScope(
					new TypeDeclarationOptions(new TypeIdentity(model.ClassName, model.Namespace), model.Accessibility)
					{
						IsPartial = true,
						IsStatic = model.IsStatic,
						IsAbstract = model.IsAbstract,
						IsSealed = model.IsSealed,
					}
				)
			)
			{
				EmitCreateMethod(writer, model, parameterNames, parameters);
				writer.NewLine();
				EmitThrowMethod(writer, model, parameterNames, parameters);
			}
		}
	}

	static void EmitCreateMethod(
		CodeWriter writer,
		ErrorTypeFieldModel model,
		ImmutableArray<string> parameterNames,
		ImmutableArray<ParameterDeclarationOptions> parameters
	)
	{
		var dictionaryName = BuildDictionaryName(parameterNames);

		writer
			.XmlSummary("Creates a ValidationError for this error type.")
			.Method(
				new MethodDeclarationOptions(
					"Create" + PascalCase(model.FieldName),
					TypeLibrary.Core.ValidationError.AsTypeReference(),
					TypeDeclarationAccessibility.Public
				)
				{
					IsStatic = true,
					Parameters = parameters,
				},
				method =>
				{
					method.OpenDelimitedBlock(
						$"global::System.Collections.Generic.Dictionary<string, object?> {dictionaryName} = new({model.Parameters.Count})",
						"{",
						"};",
						body =>
						{
							for (var i = 0; i < model.Parameters.Count; i++)
								body.Line($"[{model.Parameters[i].Surround()}] = {parameterNames[i]},");
						}
					);

					method.Line();
					method.Assignment("ErrorType", "errorType", model.FieldName);
					method.Return(
						$"ValidationError.Create(errorType.Code, errorType.FormatMessage({dictionaryName}), path is null ? [] : [.. path], {dictionaryName}, origin, minimum, maximum, inclusive)"
					);
				}
			);
	}

	static void EmitThrowMethod(
		CodeWriter writer,
		ErrorTypeFieldModel model,
		ImmutableArray<string> parameterNames,
		ImmutableArray<ParameterDeclarationOptions> parameters
	)
	{
		writer
			.XmlSummary("Throws a ZodException for this error type.")
			.Method(
				new MethodDeclarationOptions("Throw" + PascalCase(model.FieldName), TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Attributes = [new AttributeDeclarationOptions(TypeLibrary.DoesNotReturnAttribute)],
					Parameters = parameters,
				},
				method =>
				{
					var createMethod =
						"Create"
						+ PascalCase(model.FieldName)
						+ "("
						+ string.Join(
							", ",
							parameterNames.Add("path").Add("origin").Add("minimum").Add("maximum").Add("inclusive")
						)
						+ ")";
					method.Throw($"new ZodException([{createMethod}])");
				}
			);
	}

	static ImmutableArray<ParameterDeclarationOptions> BuildMethodParameters(
		ImmutableArray<string> parameterNames,
		CodeWriter writer
	)
	{
		var objectType = PurviewTypeLibrary.System.Object.AsTypeReference().Nullable(writer);
		var stringArrayType = PurviewTypeLibrary.System.String.AsTypeReference().MakeArray().Nullable(writer);
		var stringType = PurviewTypeLibrary.System.String.AsTypeReference().Nullable(writer);
		var intType = PurviewTypeLibrary.System.Int32.AsTypeReference().Nullable(writer);
		var boolType = PurviewTypeLibrary.System.Boolean.AsTypeReference().Nullable(writer);

		var builder = ImmutableArray.CreateBuilder<ParameterDeclarationOptions>(parameterNames.Length + 5);
		foreach (var name in parameterNames)
			builder.Add(new ParameterDeclarationOptions(name, objectType));

		builder.Add(new ParameterDeclarationOptions("path", stringArrayType) { DefaultValue = "null" });
		builder.Add(new ParameterDeclarationOptions("origin", stringType) { DefaultValue = "null" });
		builder.Add(new ParameterDeclarationOptions("minimum", intType) { DefaultValue = "null" });
		builder.Add(new ParameterDeclarationOptions("maximum", intType) { DefaultValue = "null" });
		builder.Add(new ParameterDeclarationOptions("inclusive", boolType) { DefaultValue = "null" });

		return builder.ToImmutable();
	}

	/// <summary>
	/// Camel-cases the declared parameter names while avoiding collisions with the reserved metadata
	/// parameter names (<c>path</c>, <c>origin</c>, <c>minimum</c>, <c>maximum</c>, <c>inclusive</c>).
	/// </summary>
	static ImmutableArray<string> BuildParameterNames(EquatableArray<string> declaredNames)
	{
		HashSet<string> used = ["path", "origin", "minimum", "maximum", "inclusive", "parameters"];

		var builder = ImmutableArray.CreateBuilder<string>(declaredNames.Count);
		foreach (var declaredName in declaredNames)
		{
			var candidate = CamelCase(declaredName);
			while (!used.Add(candidate))
				candidate += "Value";

			builder.Add(candidate);
		}

		return builder.ToImmutable();
	}

	/// <summary>
	/// Chooses a local dictionary name that does not collide with any generated method parameter.
	/// </summary>
	static string BuildDictionaryName(ImmutableArray<string> parameterNames)
	{
		HashSet<string> used = [.. parameterNames];
		var candidate = "parameters";
		while (!used.Add(candidate))
			candidate += "Value";

		return candidate;
	}

	static string PascalCase(string name)
	{
		if (name.Length == 0 || !char.IsLower(name[0]))
			return name;

		// Avoid pascal-casing names that are all lowercase (e.g., "url" -> "Url")
		return char.ToUpperInvariant(name[0]) + name.Substring(1);
	}

	static string CamelCase(string name)
	{
		if (name.Length == 0 || !char.IsUpper(name[0]))
			return name;

		// Avoid camel-casing names that are all uppercase (e.g., "URL" -> "uRL")
		return char.ToLowerInvariant(name[0]) + name.Substring(1);
	}
}
