using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using ZodSharp.AspNetCore.SourceGenerators.Helpers;
using ZodSharp.AspNetCore.SourceGenerators.Models;

namespace ZodSharp.AspNetCore.SourceGenerators;

/// <summary>
/// Generates strongly-typed <c>Create{Field}</c>/<c>Throw{Field}</c> static methods for each
/// <c>[ErrorType]</c> field declared in a partial class. The generated methods take the error
/// type's declared <c>Parameters</c> as named arguments and return a <c>ValidationError</c> /
/// throw a <c>ZodException</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class ErrorTypeGenerator : IIncrementalGenerator
{
	/// <inheritdoc />
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context
			.RegisterEmbeddedAttribute<ErrorTypeGenerator>()
			.RegisterPostInitializationOutput(static ctx =>
				ctx.AddSource("ErrorTypeAttribute.g.cs", ErrorTypeAttributeSource())
			);

		var generationContext = IncrementalPipeline.GenerationContextValueProvider<
			ErrorTypeGeneratorCapabilities,
			ErrorTypeGenerator
		>(
			context,
			static (compilation, _, _, _) => ErrorTypeGeneratorCapabilities.Create(compilation),
			PropertyLibrary.DisableAspNetCoreErrorTypeGeneratorProperty
		);

		var errorTypeFields = IncrementalPipeline.ForAttributeWithMetadataName(
			context,
			TypeLibrary.AspNetCore.ErrorTypeAttribute,
			predicate: static (node, _) => node is VariableDeclaratorSyntax,
			transform: static (attributeContext, cancellationToken) =>
				ErrorTypeGeneratorLibrary.CreateModel(attributeContext, cancellationToken),
			trackingName: "ForAttribute_ErrorTypeAttribute"
		);

		var generationModels = generationContext.CollectWith(
			errorTypeFields,
			static (context, fields, _) =>
				new ErrorTypeGenerationModel(context, new EquatableArray<GeneratorResult<ErrorTypeFieldModel>>(fields)),
			"CollectErrorTypeFields"
		);

		context.RegisterSourceOutput(
			generationModels,
			static (spc, model) =>
			{
				if (model.Context.Settings.IsSourceGeneratorDisabled)
					return;

				if (!model.Context.Capabilities.HasErrorType)
					return;

				foreach (var result in model.Fields)
				{
					foreach (var diagnostic in result.Diagnostics)
						spc.ReportDiagnostic(diagnostic.ToDiagnostic());

					if (!result.ShouldProcess)
						continue;

					try
					{
						var writer = model.Context.CreateCodeWriter();
						Emit(writer, result.Value);
						spc.AddSource(result.Value.HintName, writer);
					}
					catch (Exception ex)
					{
						spc.ReportDiagnostic(
							ReportableDiagnostic
								.Create(
									DiagnosticLibrary.UnhandledException,
									true,
									[result.Value.ClassName, ex.Message]
								)
								.ToDiagnostic()
						);
					}
				}
			}
		);
	}

	static SourceText ErrorTypeAttributeSource()
	{
		CodeWriter writer = new(GenerationSettings.Create<ErrorTypeGenerator>());

		writer.AutoGeneratedHeader().FileScopedNamespace(TypeLibrary.AspNetCore.ErrorTypeAttribute);

		writer
			.XmlSummary(
				"Attribute to mark a static ErrorType field for strongly-typed helper generation.",
				"When applied to a static ErrorType field in a partial class, Create/Throw helpers are generated at compile time."
			)
			.AttributeClass(
				new TypeDeclarationOptions(TypeLibrary.AspNetCore.ErrorTypeAttribute),
				AttributeTargets.Field,
				static _ => { },
				inherited: false,
				allowMultiple: false
			);

		return writer;
	}
}
