using Microsoft.CodeAnalysis.Text;

namespace ZodSharp.SourceGenerators.Helpers;

static class AttributeGenHelper
{
	public static IEnumerable<(string HintName, SourceText SourceText)> GenerateMarkers()
	{
		yield return ("ZodSchemaAttribute", ZodSchema());
	}

	static SourceText ZodSchema()
	{
		CodeWriter writer = new(typeof(ZodSchemaGenerator).FullName, AssemblyInfo.Version);

		writer.WriteAutoGeneratedHeader().WriteFileScopedNamespace(TypeLibrary.ZodSchemaAttribute);

		writer
			.XmlSummary(
				"Attribute to mark a class for automatic schema generation.",
				"When applied to a class, a zero-allocation validator will be generated at compile time."
			)
			.WriteClass(
				new(TypeLibrary.ZodSchemaAttribute)
				{
					Accessibility = TypeDeclarationAccessibility.Internal,
					BaseType = PurviewTypeLibrary.System.Attribute,
					Attributes =
					[
						new(TypeLibrary.System.AttributeUsageAttribute)
						{
							Arguments =
							[
								new(
									$"{TypeLibrary.System.AttributeTargets.Property("Class")} | {TypeLibrary.System.AttributeTargets.Property("Struct")}"
								),
								new(false, "AllowMultiple", true),
								new(false, "Inherited", true),
							],
						},
					],
				},
				body =>
				{
					body.XmlSummary(
							"Optional name for the generated schema class.",
							"If not specified, uses \"{ClassName}Schema\"."
						)
						.WriteProperty(new("SchemaName", TypeLibrary.System.String.Nullable()) { IsInitOnly = true });

					body.XmlSummary("Whether to generate a static Validate method.", "Default is true.")
						.WriteProperty(
							new("GenerateValidateMethod", TypeLibrary.System.Boolean)
							{
								Accessibility = TypeDeclarationAccessibility.Public,
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Whether to generate a static Parse method (throws on failure).",
							$"Default is true."
						)
						.WriteProperty(
							new("GenerateParseMethod", TypeLibrary.System.Boolean)
							{
								Accessibility = TypeDeclarationAccessibility.Public,
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Whether to enable composition methods (.and(), .or(), .refine()).",
							$"Default is true."
						)
						.WriteProperty(
							new("EnableComposition", TypeLibrary.System.Boolean)
							{
								Accessibility = TypeDeclarationAccessibility.Public,
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Optional name of a custom asynchronous validation method to invoke",
							"after synchronous validation. When set, the generator looks for a",
							"method with the signature:",
							"<c>static ValueTask&lt;ValidationResult&lt;T&gt;&gt; MethodName(T value, CancellationToken cancellationToken)</c>",
							"If null, the default name <c>CustomValidationAsync</c> is used.",
							"No diagnostic is reported when the default name has no matching method."
						)
						.WriteProperty(
							new("CustomValidationMethodName", TypeLibrary.System.String.Nullable())
							{
								Accessibility = TypeDeclarationAccessibility.Public,
								IsInitOnly = true,
							}
						);
				}
			);

		return writer;
	}
}
