using Microsoft.CodeAnalysis.Text;
using ZodSharp.SourceGenerators.Models;

namespace ZodSharp.SourceGenerators.Helpers;

static class AttributeGenHelper
{
	public static IEnumerable<(string HintName, SourceText SourceText)> GenerateMarkers()
	{
		yield return (nameof(ZodSchemaAttribute), ZodSchemaAttribute());
	}

	static SourceText ZodSchemaAttribute()
	{
		CodeWriter writer = new(GenerationSettings.Create<ZodSchemaGenerator>());

		writer.AutoGeneratedHeader().FileScopedNamespace(TypeLibrary.ZodSharp.ZodSchemaAttribute);

		writer
			.XmlSummary(
				"Attribute to mark a class for automatic schema generation.",
				"When applied to a class, a zero-allocation validator will be generated at compile time."
			)
			.AttributeClass(
				new(TypeLibrary.ZodSharp.ZodSchemaAttribute),
				AttributeTargets.Class | AttributeTargets.Struct,
				body =>
				{
					body.XmlSummary(
							"Optional name for the generated schema class.",
							"If not specified, uses \"{ClassName}Schema\"."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.SchemaName),
								PurviewTypeLibrary.System.String.AsTypeReference().Nullable(body),
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
							}
						);

					body.XmlSummary("Whether to generate a static Validate method.", "Default is true.")
						.Property(
							new(
								nameof(ZodSchemaAttributeData.GenerateValidateMethod),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Whether to generate a static Parse method (throws on failure).",
							$"Default is true."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.GenerateParseMethod),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Whether to enable composition methods (.and(), .or(), .refine()).",
							$"Default is true."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.EnableComposition),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Optional name of a custom asynchronous validation method to invoke",
							"after synchronous validation. When set, the generator looks for a",
							"method with the signature:",
							"<c>static ValueTask&lt;ValidationResult&lt;T&gt;&gt; MethodName(T value, CancellationToken cancellationToken)</c>",
							"If null, the default name <c>CustomValidationAsync</c> is used.",
							"No diagnostic is reported when the default name has no matching method."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.CustomValidationMethodName),
								PurviewTypeLibrary.System.String.AsTypeReference().Nullable(body),
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
							}
						);
				}
			);

		return writer;
	}
}
