using Microsoft.CodeAnalysis.Text;
using ZodSharp.SourceGenerators.Models;

namespace ZodSharp.SourceGenerators.Helpers;

static class AttributeGenHelper
{
	public static IEnumerable<(string HintName, SourceText SourceText)> GenerateMarkers()
	{
		yield return (nameof(ZodSchemaAttribute), ZodSchemaAttribute());
	}

	static SourceText ZodSchemaAttribute()
	{
		CodeWriter writer = new(GenerationSettings.Create<ZodSchemaGenerator>());

		writer.AutoGeneratedHeader().FileScopedNamespace(TypeLibrary.ZodSharp.ZodSchemaAttribute);

		writer
			.XmlSummary(
				"Attribute to mark a class for automatic schema generation.",
				"When applied to a class, a zero-allocation validator will be generated at compile time."
			)
			.AttributeClass(
				new(TypeLibrary.ZodSharp.ZodSchemaAttribute),
				AttributeTargets.Class | AttributeTargets.Struct,
				body =>
				{
					body.XmlSummary(
							"Optional name for the generated schema class.",
							"If not specified, uses \"{ClassName}Schema\"."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.SchemaName),
								PurviewTypeLibrary.System.String.AsTypeReference().Nullable(body),
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
							}
						);

					body.XmlSummary("Whether to generate a static Validate method.", "Default is true.")
						.Property(
							new(
								nameof(ZodSchemaAttributeData.GenerateValidateMethod),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Whether to generate a static Parse method (throws on failure).",
							$"Default is true."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.GenerateParseMethod),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Whether to enable composition methods (.and(), .or(), .refine()).",
							$"Default is true."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.EnableComposition),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "true",
							}
						);

					body.XmlSummary(
							"Optional name of a custom asynchronous validation method to invoke",
							"after synchronous validation. When set, the generator looks for a",
							"method with the signature:",
							"<c>ValueTask&lt;ValidationResult&lt;T&gt;&gt; MethodName(T value, CancellationToken cancellationToken)</c>",
							"declared as a static method on the model type or an instance method on the",
							"generated <c>{TypeName}SchemaValidator</c> partial.",
							"If null, the default name <c>CustomValidationAsync</c> is used.",
							"No diagnostic is reported when the default name has no matching method.",
							"Mutually exclusive with <c>RefinementMethodName</c> (ZODSGEN029)."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.CustomValidationMethodName),
								PurviewTypeLibrary.System.String.AsTypeReference().Nullable(body),
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
							}
						);

					body.XmlSummary(
							"Optional name of a synchronous refinement method to invoke",
							"during synchronous validation. When set, the generator looks for an",
							"instance method on the model type with the signature:",
							"<c>IEnumerable&lt;ValidationError&gt; MethodName()</c> or",
							"<c>IEnumerable&lt;ValidationError&gt; MethodName(RefineCtx&lt;T&gt; ctx)</c>.",
							"If null, the default name <c>Validate</c> is used.",
							"No diagnostic is reported when the default name has no matching method.",
							"Mutually exclusive with <c>CustomValidationMethodName</c> (ZODSGEN029)."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.RefinementMethodName),
								PurviewTypeLibrary.System.String.AsTypeReference().Nullable(body),
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
							}
						);

					body.XmlSummary(
							"Whether to generate an <c>IValidateOptions&lt;T&gt;</c> validator for this type.",
							"Generation is driven by auto-detection by default: enabled when the type name ends",
							"with a configured suffix (e.g. <c>Options</c> or <c>Settings</c>) and the",
							"<c>ZodSharpAutoGenerateOptionsValidators</c> MSBuild property is not disabled.",
							"Set to true to force generation or set <c>SuppressIValidateOptions</c> to opt out."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.GenerateIValidateOptions),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "false",
							}
						);

					body.XmlSummary(
							"Suppresses generation of the <c>IValidateOptions&lt;T&gt;</c> validator for this type,",
							"even when auto-detection would otherwise enable it."
						)
						.Property(
							new(
								nameof(ZodSchemaAttributeData.SuppressIValidateOptions),
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								IsInitOnly = true,
								Initializer = "false",
							}
						);
				}
			);

		return writer;
	}
}
