using System.Collections.Concurrent;
using Microsoft.CodeAnalysis;

namespace ZodSharp.SourceGenerators.Helpers;

/// <summary>
/// Decides which compilation owns the schema for a complex type, and resolves the schema that the
/// assembly declaring the type already generated for it.
/// </summary>
/// <remarks>
/// <para>
/// A schema for <c>{Type}</c> is always emitted into the namespace of <c>{Type}</c> and named
/// <c>{Type}Schema</c>, so two compilations that both consider themselves the owner declare the same
/// fully-qualified type name. The consuming compilation then reports CS0436 ("conflicts with the imported
/// type") and binds to a different schema than the assembly that declares the type.
/// </para>
/// <para>
/// The generator emits <c>[assembly: ZodSchemaGenerated(typeof(T))]</c> for every top-level primary schema
/// and the runtime <c>RegisterFromAssembly</c> discovery reads the same marker, so the marker is the
/// authoritative "a schema already exists for this type" signal.
/// </para>
/// <para>
/// An instance is created per generation pass (per compilation for the analyzer) and retains no symbols:
/// the cache keys and values are value types only, so nothing from a compilation outlives the pass.
/// </para>
/// </remarks>
sealed class ExternalSchemaResolver
{
	readonly Compilation _compilation;
	readonly ConcurrentDictionary<(TypeIdentity Type, AssemblyIdentity Assembly), Resolution> _resolved = new();

	/// <summary>
	/// Initializes a new instance of the <see cref="ExternalSchemaResolver"/> class.
	/// </summary>
	/// <param name="compilation">The compilation currently being generated.</param>
	/// <exception cref="ArgumentNullException">Thrown when <paramref name="compilation"/> is null.</exception>
	public ExternalSchemaResolver(Compilation compilation) =>
		_compilation = compilation ?? throw new ArgumentNullException(nameof(compilation));

	/// <summary>
	/// Determines whether the compilation currently being generated declares <paramref name="type"/>.
	/// </summary>
	/// <param name="type">The type to test.</param>
	/// <returns><see langword="true"/> when the type belongs to the current compilation.</returns>
	public bool IsDeclaredInThisCompilation(INamedTypeSymbol type) =>
		SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, _compilation.Assembly);

	/// <summary>
	/// Determines whether this compilation is allowed to emit <c>{Type}Schema</c> for
	/// <paramref name="type"/>: the type must be declared here and have a schema-able shape.
	/// </summary>
	/// <param name="type">The type to test.</param>
	/// <returns><see langword="true"/> when the schema for <paramref name="type"/> is owned by this compilation.</returns>
	public bool IsSchemaOwnedByThisCompilation(INamedTypeSymbol type) =>
		IsDeclaredInThisCompilation(type) && HasSchemaShape(type);

	/// <summary>
	/// Resolves the schema generated by the assembly declaring <paramref name="type"/>, when that assembly
	/// published one and it is usable from the compilation currently being generated.
	/// </summary>
	/// <param name="type">The complex property type to resolve an existing schema for.</param>
	/// <param name="schemaType">The identity of the existing schema when one was found.</param>
	/// <returns><see langword="true"/> when an existing, accessible schema was found.</returns>
	public bool TryGetExistingSchema(INamedTypeSymbol type, out TypeIdentity schemaType)
	{
		if (type.ContainingAssembly?.Identity is not { } assembly)
		{
			schemaType = default;
			return false;
		}

		var key = (Type: new TypeIdentity(type), Assembly: assembly);
		if (!_resolved.TryGetValue(key, out var resolution))
		{
			var resolved = Resolve(type);
			resolution = resolved is { } value ? new(Found: true, Schema: value) : default;
			_resolved[key] = resolution;
		}

		schemaType = resolution.Schema;
		return resolution.Found;
	}

	TypeIdentity? Resolve(INamedTypeSymbol type)
	{
		// The declaring compilation owns the schema; only another assembly can already have generated one.
		if (IsDeclaredInThisCompilation(type) || !HasSchemaShape(type))
			return null;

		if (type.ContainingAssembly is not { } assembly)
			return null;

		TypeIdentity identity = new(type);
		if (!HasGeneratedSchemaMarker(assembly, identity))
			return null;

		var schema = identity with { Name = $"{identity.Name}Schema" };
		if (_compilation.GetTypeByMetadataName(schema.MetadataFullName) is not INamedTypeSymbol schemaSymbol)
			return null;

		// The schema has to come from the same assembly as the type, and consumers have to be able to see it.
		if (
			!SymbolEqualityComparer.Default.Equals(schemaSymbol.ContainingAssembly, assembly)
			|| !IsPubliclyAccessible(schemaSymbol)
		)
		{
			return null;
		}

		return schema;
	}

	static bool HasGeneratedSchemaMarker(IAssemblySymbol assembly, TypeIdentity targetType)
	{
		foreach (var attribute in assembly.GetAttributes())
		{
			if (
				!TypeLibrary.ZodSharp.Core.ZodSchemaGeneratedAttribute.Matches(attribute.AttributeClass)
				|| attribute.ConstructorArguments.Length == 0
			)
			{
				continue;
			}

			if (attribute.ConstructorArguments[0].Value is ITypeSymbol marked && targetType.Matches(marked))
				return true;
		}

		return false;
	}

	static bool IsPubliclyAccessible(INamedTypeSymbol type)
	{
		for (var current = (INamedTypeSymbol?)type; current is not null; current = current.ContainingType)
		{
			if (current.DeclaredAccessibility != Accessibility.Public)
				return false;
		}

		return true;
	}

	static bool HasSchemaShape(INamedTypeSymbol type) =>
		type.TypeKind is TypeKind.Class or TypeKind.Struct && !type.IsAbstract && !type.IsStatic;

	/// <summary>
	/// The cached outcome of resolving an existing schema: the schema identity when one was found.
	/// </summary>
	/// <param name="Found">Whether an existing accessible schema was found.</param>
	/// <param name="Schema">The identity of the existing schema when <paramref name="Found"/> is true.</param>
	readonly record struct Resolution(bool Found, TypeIdentity Schema);
}
