using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using ZodSharp.SourceGenerators.Helpers;
using ZodSharp.SourceGenerators.Models;
using ZodSharp.SourceGenerators.Models.DataAttributes;

namespace ZodSharp.SourceGenerators;

partial class ZodSchemaGenerator
{
	static void BuildSchema(
		INamedTypeSymbol schemaSymbol,
		TypeIdentity schemaType,
		SchemaGenerationOutputContext outputContext,
		SourceProductionContext context,
		bool isPrimary
	)
	{
		outputContext.Info($"Building schema for {schemaSymbol.Name}");

		try
		{
			List<DiagnosticInfo> diagnostics = [];
			var source = GenerateSchemaClass(schemaSymbol, outputContext, diagnostics, isPrimary);
			if (diagnostics.Count > 0)
				ReportDiagnostics(context, diagnostics, outputContext);

			var fileName = $"{schemaSymbol.Name}Schema.g.cs";
			context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));

			// Emit module-level registration attribute for DI discovery.
			// For typeof, nested types use the CLR '+' separator (e.g. Outer+Inner).
			// Skip registration for nested types because private nested types are inaccessible at
			// assembly scope and public/internal nested types are best discovered through their
			// containing type.
			if (isPrimary && schemaSymbol.ContainingType is null)
			{
				// Create a new writer for the assembly-level attribute to avoid polluting the schema class file.
				var writer = outputContext.Context.CreateCodeWriter();

				writer.WriteAutoGeneratedHeader();
				writer
					.Write("[assembly: global::")
					.Write(TypeLibrary.ZodSchemaGeneratedAttribute.MetadataFullName)
					.Write("(typeof(")
					.Write(schemaType)
					.WriteLine("))]");

				context.AddSource(
					$"{schemaSymbol.Name}SchemaRegistration.g.cs",
					SourceText.From(writer.ToString(), Encoding.UTF8)
				);
			}
		}
		catch (CodeWriterScopeValidationException)
		{
			// This is an opt-in framework invariant failure. Let Roslyn and the test
			// harness retain the exception instead of reducing it to ZODSGEN001.
			throw;
		}
		catch (Exception ex)
		{
			// Report diagnostic if generation fails
			var diagnostic = DiagnosticInfo.Create(
				DiagnosticLibrary.UnhandledException,
				schemaSymbol,
				schemaSymbol.Name,
				ex.Message
			);

			ReportDiagnostics(context, diagnostic, outputContext);
		}
	}

	internal static bool IsScalarType(INamedTypeSymbol type) =>
		type.SpecialType
			is SpecialType.System_Boolean
				or SpecialType.System_Char
				or SpecialType.System_SByte
				or SpecialType.System_Byte
				or SpecialType.System_Int16
				or SpecialType.System_UInt16
				or SpecialType.System_Int32
				or SpecialType.System_UInt32
				or SpecialType.System_Int64
				or SpecialType.System_UInt64
				or SpecialType.System_Single
				or SpecialType.System_Double
				or SpecialType.System_Decimal
				or SpecialType.System_String
				or SpecialType.System_DateTime
				or SpecialType.System_Object
				or SpecialType.System_IntPtr
				or SpecialType.System_UIntPtr;

	static string GenerateSchemaClass(
		INamedTypeSymbol classSymbol,
		SchemaGenerationOutputContext outputContext,
		List<DiagnosticInfo> diagnostics,
		bool isPrimary
	)
	{
		var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
		var className = classSymbol.Name;
		var schemaName = $"{className}Schema";
		var codeTypeName = GetFullyQualifiedCodeTypeName(classSymbol);
		var modifier = GetSchemaClassAccessibilityKeyword(classSymbol);

		outputContext.Info($"Generating schema {schemaName} ({modifier}) for {className} in namespace {namespaceName}");

		// Estimate capacity based on the number of properties
		var propertyCount = classSymbol
			.GetMembers()
			.OfType<IPropertySymbol>()
			.Count(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

		outputContext.Info($"Property count for {className}: {propertyCount}", 1);

		var writer = outputContext.Writer;

		writer.WriteAutoGeneratedHeader();
		writer
			.WriteUsing("System")
			.WriteUsing("System.Collections.Generic")
			.WriteUsing("System.Collections.Immutable")
			.WriteUsing(TypeLibrary.ZodSharpCoreNamespace)
			.NewLine();

		using (writer.WriteBlockNamespaceScope(namespaceName))
		{
			writer.XmlSummary(
				$"Auto-generated schema validator for {className}.",
				"This class is generated at compile time for zero-allocation validation."
			);

			var containingTypes = GetContainingTypeChain(classSymbol);
			List<IDisposable> wrapperBlocks = [];
			foreach (var containingType in containingTypes)
			{
				wrapperBlocks.Add(
					writer.WriteTypeScope(TypeHelpers.CreatePartialTypeDeclarationOptions(containingType))
				);
			}

			using (
				writer.WriteClassScope(
					new(schemaName)
					{
						IsPartial = true,
						IsStatic = true,
						Accessibility = classSymbol.ContainingType is null
							? classSymbol.DeclaredAccessibility == Accessibility.Public
								? TypeDeclarationAccessibility.Public
								: TypeDeclarationAccessibility.Internal
							: classSymbol.DeclaredAccessibility.ToTypeDeclarationAccessibility(),
					}
				)
			)
			{
				writer.WriteField(
					new(
						"EmptyPath",
						TypeLibrary.Collections.ImmutableArray.MakeGeneric(PurviewTypeLibrary.System.String)
					)
					{
						Accessibility = TypeDeclarationAccessibility.Private,
						IsStatic = true,
						IsReadOnly = true,
						Initializer = "[]",
					}
				);

				GeneratePathFields(outputContext, classSymbol);
				GenerateStaticAttributeFields(outputContext, classSymbol, diagnostics);
				GenerateValidationHelpers(outputContext);

				GenerateValidateMethod(outputContext, classSymbol, codeTypeName, diagnostics);
				GenerateParseMethod(outputContext, codeTypeName);

				// Emit the value-first composition methods (ApplyAnd/ApplyOr/ApplyRefine).
				GenerateCompositionMethods(outputContext, classSymbol, codeTypeName);
			}

			// Only primary schemas get a validator adapter and custom validation lookup.
			if (isPrimary)
			{
				// Resolve the optional custom async validation method from [ZodSchema(CustomValidationMethodName = ...)].
				var customValidation = ResolveCustomValidationMethod(classSymbol);
				if (customValidation.Diagnostics.Length > 0)
					diagnostics.AddRange(customValidation.Diagnostics);

				GenerateValidatorAdapter(
					outputContext,
					classSymbol,
					schemaName,
					codeTypeName,
					modifier,
					customValidation
				);
			}

			foreach (var block in wrapperBlocks)
				block.Dispose();
		}

		return writer.ToString();
	}

	static ImmutableArray<INamedTypeSymbol> GetContainingTypeChain(INamedTypeSymbol typeSymbol)
	{
		var chain = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
		var current = typeSymbol.ContainingType;
		while (current is not null)
		{
			chain.Add(current);
			current = current.ContainingType;
		}

		chain.Reverse();
		return chain.ToImmutable();
	}

	static string GetSchemaClassAccessibilityKeyword(INamedTypeSymbol symbol) =>
		symbol.ContainingType is null
			? TypeHelpers.GetLimitedAccessibilityKeyword(symbol)
			: TypeHelpers.GetAccessibilityKeyword(symbol.DeclaredAccessibility);

	static string GetFullyQualifiedCodeTypeName(INamedTypeSymbol typeSymbol)
	{
		var sb = new StringBuilder();
		sb.Append("global::");

		var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
		if (!string.IsNullOrEmpty(namespaceName))
		{
			sb.Append(namespaceName);
			sb.Append('.');
		}

		var containingTypes = new List<INamedTypeSymbol>();
		var current = typeSymbol.ContainingType;
		while (current is not null)
		{
			containingTypes.Add(current);
			current = current.ContainingType;
		}

		containingTypes.Reverse();

		foreach (var containingType in containingTypes)
		{
			sb.Append(containingType.Name);
			sb.Append('.');
		}

		sb.Append(typeSymbol.Name);
		return sb.ToString();
	}

	/// <summary>
	/// Generates a DI-friendly instance adapter class that delegates to the static {ClassName}Schema.Validate method.
	/// </summary>
	static void GenerateValidatorAdapter(
		SchemaGenerationOutputContext outputContext,
		INamedTypeSymbol classSymbol,
		string schemaName,
		string fullTypeName,
		string modifier,
		CustomValidationMethodData customValidation
	)
	{
		outputContext.Writer.WriteLine();
		outputContext.Writer.XmlSummary(
			$"DI-friendly validator adapter for {classSymbol.Name}, delegating to {schemaName}."
		);
		using (
			outputContext.Writer.OpenBlockScope(
				$"{modifier} sealed partial class {schemaName}Validator : global::ZodSharp.Core.IZodSchemaValidator<{fullTypeName}>"
			)
		)
		{
			outputContext.Writer.WriteLine(
				$"public global::ZodSharp.Core.ValidationResult<{fullTypeName}> Validate({fullTypeName} value)"
			);
			using (outputContext.Writer.OpenBlockScope())
			{
				outputContext.Writer.WriteLine($"return {schemaName}.Validate(value);");
			}

			outputContext.Writer.WriteLine();
			GenerateValidateAsyncMethod(outputContext, schemaName, fullTypeName, customValidation);
		}
	}

	/// <summary>
	/// Generates the ValidateAsync method on the adapter. When a valid custom async
	/// validation method exists, it awaits the custom method and merges results.
	/// Otherwise, it returns the synchronous result in a completed ValueTask
	/// without an async state machine.
	/// </summary>
	static void GenerateValidateAsyncMethod(
		SchemaGenerationOutputContext outputContext,
		string schemaName,
		string fullTypeName,
		CustomValidationMethodData customValidation
	)
	{
		outputContext.Info(
			$"Generating ValidateAsync method for {schemaName}Validator with custom validation: {customValidation.MethodName}",
			1
		);

		var validationResultGlobal = TypeLibrary.ValidationResult;
		var ctParam = "global::System.Threading.CancellationToken cancellationToken = default";

		if (!customValidation.HasCustomValidation)
		{
			// No custom method — synchronous fallback, no async state machine.
			outputContext.Writer.WriteLine(
				$"public global::System.Threading.Tasks.ValueTask<{validationResultGlobal}<{fullTypeName}>> ValidateAsync({fullTypeName} value, {ctParam})"
			);
			using (outputContext.Writer.OpenBlockScope())
			{
				outputContext.Writer.WriteLine(
					$"return global::System.Threading.Tasks.ValueTask.FromResult({schemaName}.Validate(value));"
				);
			}

			return;
		}

		// Custom async validation path — async state machine is required here.
		outputContext.Writer.WriteLine(
			$"public async global::System.Threading.Tasks.ValueTask<{validationResultGlobal}<{fullTypeName}>> ValidateAsync({fullTypeName} value, {ctParam})"
		);
		using (outputContext.Writer.OpenBlockScope())
		{
			outputContext.Writer.WriteLine($"var syncResult = {schemaName}.Validate(value);");

			var escapedMethodName = customValidation.MethodName;
			var validationMethodPrefix =
				customValidation.InvocationKind == CustomValidationInvocationKind.DefinedOnSchemaValidator
					? ""
					: $"{fullTypeName}.";

			outputContext.Writer.WriteLine(
				$"var customResult = await {validationMethodPrefix}{escapedMethodName}(value, cancellationToken).ConfigureAwait(false);"
			);

			outputContext.Writer.WriteLine();
			outputContext.Writer.WriteLine(
				$"return {validationResultGlobal.MakeGeneric(fullTypeName)}.Merge(syncResult, customResult);"
			);
		}
	}

	static void GenerateValidateMethod(
		SchemaGenerationOutputContext outputContext,
		INamedTypeSymbol classSymbol,
		string fullTypeName,
		List<DiagnosticInfo> diagnostics
	)
	{
		outputContext
			.Writer.XmlSummary("Validates an instance of the target type.")
			.WriteLine(
				$"public static {TypeLibrary.ValidationResult.MakeGeneric(fullTypeName)} Validate({fullTypeName} value)"
			);

		using (outputContext.Writer.OpenBlockScope())
		{
			if (TypeHelpers.CanBeNull(classSymbol))
			{
				outputContext.Writer.WriteBlock(
					"if (value == null)",
					ifBody =>
						ifBody.WriteDelimitedBlock(
							$"return {TypeLibrary.ValidationResult.MakeGeneric(fullTypeName)}.Failure",
							"(",
							");",
							failureArguments =>
								failureArguments.WriteDelimitedBlock(
									$"{TypeLibrary.ValidationError}.Create",
									"(",
									")",
									errorArguments =>
									{
										errorArguments.Quote("invalid_type").WriteLine(",");
										errorArguments.Quote("Value cannot be null").WriteLine(",");
										errorArguments.WriteLine("EmptyPath");
									}
								)
						)
				);
			}

			outputContext
				.Writer.NewLine()
				.WriteLine($"{TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError)}? errors = null;");

			var properties = classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
				.ToList();

			foreach (var property in properties)
				GeneratePropertyValidation(outputContext, property, diagnostics);

			using (outputContext.Writer.OpenBlockScope("if (errors is not null)"))
			{
				outputContext.Writer.WriteLine(
					$"return {TypeLibrary.ValidationResult}<{fullTypeName}>.Failure(errors);"
				);
			}

			outputContext
				.Writer.WriteLine()
				.WriteLine($"return {TypeLibrary.ValidationResult}<{fullTypeName}>.Success(value);");
		}

		outputContext.Writer.NewLine();
	}

	static void GeneratePropertyValidation(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		List<DiagnosticInfo> diagnostics
	)
	{
		var propertyName = property.Name;
#pragma warning disable format
		var propertyType = property.Type
			is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullableType
			? nullableType.TypeArguments[0]
			: property.Type;
#pragma warning restore format

		var canBeNull = TypeHelpers.CanBeNull(property.Type);
		var attributes = property.GetAttributes();
		var requiredAttrib = RequiredAttributeData.FromAttributeData(attributes);

		CodeWriter.BlockScope? block = null;
		if (canBeNull && requiredAttrib.Exists)
		{
			var isStringAndAllowEmptyStrings =
				propertyType.SpecialType == SpecialType.System_String && requiredAttrib.AllowEmptyStrings;
			var localErrorMessage = isStringAndAllowEmptyStrings
				? "Field '{0}' is required and cannot be null or empty"
				: "Required field '{0}' is null";

			var errorMessage = string.Format(
				CultureInfo.InvariantCulture,
				requiredAttrib.ValidationAttribute.ErrorMessage ?? localErrorMessage,
				propertyName
			);

			var comparision = isStringAndAllowEmptyStrings
				? $"string.IsNullOrEmpty(value.{propertyName})"
				: $"value.{propertyName} == null";

			outputContext.Writer.WriteRule(propertyName, comparision, "missing_field", errorMessage);

			block = outputContext.Writer.OpenBlockScope("else");
			GenerateValueSetValidations(outputContext, property, property.Type, propertyName, attributes, diagnostics);
		}
		else
		{
			GenerateValueSetValidations(outputContext, property, property.Type, propertyName, attributes, diagnostics);

			if (canBeNull)
				block = outputContext.Writer.OpenBlockScope($"if (value.{propertyName} != null)");
		}

		GenerateTypeSpecificValidations(
			outputContext,
			property,
			propertyType,
			attributes,
			propertyName,
			canBeNull,
			diagnostics
		);

		block?.Dispose();

		GenerateCompareValidation(
			outputContext,
			property,
			property.ContainingType,
			attributes,
			propertyName,
			diagnostics
		);

		outputContext.Writer.WriteLine();
	}

	static void GenerateTypeSpecificValidations(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		ITypeSymbol propertyType,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		bool canBeNull,
		List<DiagnosticInfo> diagnostics
	)
	{
		LengthAttributeData.FromAttributeData(attributes, out var lengthAttributeData);
		var supportsLengthAttribute =
			propertyType.SpecialType == SpecialType.System_String
			|| propertyType is IArrayTypeSymbol
			|| TypeHelpers.IsOrImplements(propertyType, TypeLibrary.Collections.IEnumerable)
			|| TypeHelpers.IsOrImplements(propertyType, TypeLibrary.Collections.IEnumerableT);

		if (lengthAttributeData is not null && !supportsLengthAttribute)
		{
			AddUnsupportedLengthTargetDiagnostic(diagnostics, lengthAttributeData, propertyName, propertyType);
		}

		var rangeAttribute = RangeAttributeData.FromAttributeData(attributes, out var rangeAttributeData);
		if (
			rangeAttributeData is not null
			&& !TryBuildRangeBoundaryExpressions(propertyType, rangeAttribute, out _, out _)
		)
		{
			AddUnsupportedDataAnnotationsDiagnostic(
				diagnostics,
				rangeAttributeData,
				string.Format(
					CultureInfo.InvariantCulture,
					"RangeAttribute on '{0}' cannot be generated safely for '{1}'.",
					propertyName,
					propertyType.ToDisplayString()
				)
			);
		}

		if (propertyType.SpecialType != SpecialType.System_String)
		{
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.UrlAttribute,
				nameof(TypeLibrary.DataAnnotations.UrlAttribute)
			);
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.PhoneAttribute,
				nameof(TypeLibrary.DataAnnotations.PhoneAttribute)
			);
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.CreditCardAttribute,
				nameof(TypeLibrary.DataAnnotations.CreditCardAttribute)
			);
			CheckUnsupportedStringOnlyAttribute(
				diagnostics,
				attributes,
				propertyName,
				propertyType,
				TypeLibrary.DataAnnotations.Base64StringAttribute,
				nameof(TypeLibrary.DataAnnotations.Base64StringAttribute)
			);
		}

		if (propertyType.SpecialType == SpecialType.System_String)
		{
			GenerateStringValidations(outputContext, property, propertyName, attributes, diagnostics);
		}
		else if (TypeHelpers.IsNumericType(propertyType))
		{
			GenerateNumericValidations(outputContext, property, propertyType, propertyName, attributes, diagnostics);
		}
		else if (
			propertyType is IArrayTypeSymbol
			|| TypeHelpers.Implements(propertyType, TypeLibrary.Collections.IEnumerable)
			|| TypeHelpers.Implements(propertyType, TypeLibrary.Collections.IEnumerableT)
		)
		{
			GenerateCollectionValidations(outputContext, property, propertyType, propertyName, attributes, diagnostics);

			var elementType = GetCollectionElementType(propertyType);
			if (
				elementType is INamedTypeSymbol namedElementType
				&& (TypeHelpers.HasZodSchemaAttribute(namedElementType) || IsSourceDefinedComplexType(namedElementType))
			)
			{
				GenerateCollectionElementValidation(outputContext, property, elementType, propertyName);
			}
		}
		else if (
			propertyType is INamedTypeSymbol namedPropertyType
			&& (TypeHelpers.HasZodSchemaAttribute(namedPropertyType) || IsSourceDefinedComplexType(namedPropertyType))
		)
		{
			GenerateComplexTypeValidation(outputContext, property, propertyType, propertyName, canBeNull);
		}
	}

	static void CheckUnsupportedStringOnlyAttribute(
		List<DiagnosticInfo> diagnostics,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		ITypeSymbol propertyType,
		TypeIdentity attributeType,
		string attributeName
	)
	{
		var attributeData = attributes.FirstOrDefault(a => attributeType.Equals(a.AttributeClass));
		if (attributeData is null)
			return;

		AddUnsupportedDataAnnotationsDiagnostic(
			diagnostics,
			attributeData,
			string.Format(
				CultureInfo.InvariantCulture,
				"{0} on '{1}' cannot be generated safely for '{2}'.",
				attributeName,
				propertyName,
				propertyType.ToDisplayString()
			)
		);
	}

	static void GenerateCompareValidation(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		INamedTypeSymbol? containingType,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		List<DiagnosticInfo> diagnostics
	)
	{
		var compareAttribute = CompareAttributeData.FromAttributeData(attributes);
		if (!compareAttribute.Exists)
			return;

		var otherPropertyName = compareAttribute.OtherProperty;
		var otherProperty = containingType?.GetMembers(otherPropertyName).OfType<IPropertySymbol>().FirstOrDefault();
		if (otherProperty is null)
		{
			diagnostics.Add(
				DiagnosticInfo.Create(
					DiagnosticLibrary.ComparePropertyNotFound,
					property.Locations.FirstOrDefault(),
					propertyName,
					otherPropertyName
				)
			);
			return;
		}

		var displayName = GetDisplayName(property);
		var otherDisplayName =
			compareAttribute.OtherPropertyDisplayName ?? GetDisplayName(otherProperty) ?? otherPropertyName;
		var messageExpression = BuildMessageExpression(
			outputContext,
			diagnostics,
			attributes.FirstOrDefault(static a =>
				TypeLibrary.DataAnnotations.CompareAttribute.Equals(a.AttributeClass)
			),
			displayName,
			compareAttribute.ValidationAttribute,
			CodeGenHelpers.Quote($"Field '{displayName}' must match '{otherDisplayName}'.")
		);

		using (
			outputContext.Writer.OpenBlockScope(
				$"if (!global::System.Collections.Generic.EqualityComparer<object>.Default.Equals(value.{propertyName}, value.{otherPropertyName}))"
			)
		)
		{
			WriteValidationError(
				outputContext,
				"mismatch",
				messageExpression,
				CodeGenHelpers.GetPathFieldName(propertyName)
			);
		}

		outputContext.Writer.WriteLine();
	}

	static bool IsSourceDefinedComplexType(INamedTypeSymbol type) =>
		type.Locations.Any(static l => l.IsInSource) && IsComplexType(type);

	static bool IsComplexType(INamedTypeSymbol type) => !IsScalarType(type) && type.TypeKind is not TypeKind.Enum;

	static ITypeSymbol? GetCollectionElementType(ITypeSymbol propertyType)
	{
		if (propertyType is IArrayTypeSymbol arrayType)
			return arrayType.ElementType;

		if (propertyType is not INamedTypeSymbol namedType)
			return null;

		foreach (var iface in namedType.AllInterfaces)
		{
			if (TypeHelpers.Implements(iface, TypeLibrary.Collections.IEnumerableT))
				return iface.TypeArguments[0];
		}

		if (namedType.IsGenericType && TypeHelpers.Implements(namedType, TypeLibrary.Collections.IEnumerableT))
			return namedType.TypeArguments[0];

		// If the property type implements IEnumerable but not IEnumerable<T>, we cannot determine the element type.
		return null;
	}

	static void GenerateCollectionElementValidation(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		ITypeSymbol elementType,
		string propertyName
	)
	{
		outputContext.Debug(
			$"Generating collection element validation for property '{property.Name}' of type '{elementType.ToDisplayString()}'",
			1
		);

		var schemaTypeName = TypeHelpers.GetFullSchemaTypeName((INamedTypeSymbol)elementType);
		var collectionValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Collection");
		var itemValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Item");
		var itemResultName = CodeGenHelpers.GetLocalIdentifier(propertyName, "ItemResult");
		var indexName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Index");
		var canItemBeNull = TypeHelpers.CanBeNull(elementType);

		outputContext.Writer.WriteLine($"var {collectionValueName} = value.{propertyName};");
		using (outputContext.Writer.OpenBlockScope($"if ({collectionValueName} is not null)"))
		{
			outputContext.Writer.WriteLine($"var {indexName} = 0;");
			using (outputContext.Writer.OpenBlockScope($"foreach (var {itemValueName} in {collectionValueName})"))
			{
				if (canItemBeNull)
				{
					using (outputContext.Writer.OpenBlockScope($"if ({itemValueName} is not null)"))
					{
						outputContext.Writer.WriteLine(
							$"var {itemResultName} = {schemaTypeName}.Validate({itemValueName});"
						);
						using (outputContext.Writer.OpenBlockScope($"if (!{itemResultName}.IsSuccess)"))
						{
							outputContext.Writer.WriteLine(
								$"AddNestedErrors(ref errors, {itemResultName}, {CodeGenHelpers.Quote(propertyName)}, {indexName});"
							);
						}
					}
				}
				else
				{
					outputContext.Writer.WriteLine(
						$"var {itemResultName} = {schemaTypeName}.Validate({itemValueName});"
					);
					using (outputContext.Writer.OpenBlockScope($"if (!{itemResultName}.IsSuccess)"))
					{
						outputContext.Writer.WriteLine(
							$"AddNestedErrors(ref errors, {itemResultName}, {CodeGenHelpers.Quote(propertyName)}, {indexName});"
						);
					}
				}

				outputContext.Writer.WriteLine($"{indexName}++;");
			}
		}

		outputContext.Writer.WriteLine();
	}

	static void GenerateComplexTypeValidation(
		SchemaGenerationOutputContext outputContext,
		IPropertySymbol property,
		ITypeSymbol propertyType,
		string propertyName,
		bool canBeNull
	)
	{
		outputContext.Debug(
			$"Generating complex type validation for property '{property.Name}' of type '{propertyType.ToDisplayString()}'",
			1
		);
		var propertyValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Value");
		var nestedResultName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Result");
		var schemaTypeName = TypeHelpers.GetFullSchemaTypeName((INamedTypeSymbol)propertyType);

		outputContext.Writer.WriteLine($"var {propertyValueName} = value.{propertyName};");
		if (canBeNull)
		{
			using (outputContext.Writer.OpenBlockScope($"if ({propertyValueName} is not null)"))
			{
				outputContext.Writer.WriteLine(
					$"var {nestedResultName} = {schemaTypeName}.Validate({propertyValueName});"
				);
				using (outputContext.Writer.OpenBlockScope($"if (!{nestedResultName}.IsSuccess)"))
				{
					outputContext.Writer.WriteLine(
						$"AddNestedErrors(ref errors, {nestedResultName}, {CodeGenHelpers.Quote(propertyName)});"
					);
				}
			}
		}
		else
		{
			outputContext.Writer.WriteLine($"var {nestedResultName} = {schemaTypeName}.Validate({propertyValueName});");
			using (outputContext.Writer.OpenBlockScope($"if (!{nestedResultName}.IsSuccess)"))
			{
				outputContext.Writer.WriteLine(
					$"AddNestedErrors(ref errors, {nestedResultName}, {CodeGenHelpers.Quote(propertyName)});"
				);
			}
		}
	}

	static void GeneratePathFields(SchemaGenerationOutputContext outputContext, INamedTypeSymbol classSymbol)
	{
		foreach (
			var property in classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
		)
		{
			outputContext.Writer.WriteLine(
				$"static readonly {TypeLibrary.Collections.ImmutableArray.MakeGeneric(PurviewTypeLibrary.System.String)} {CodeGenHelpers.GetPathFieldName(property.Name)} = {TypeLibrary.Collections.ImmutableArray}.Create({CodeGenHelpers.Quote(property.Name)});"
			);
		}

		outputContext.Writer.WriteLine();
	}

	static void GenerateStaticAttributeFields(
		SchemaGenerationOutputContext outputContext,
		INamedTypeSymbol classSymbol,
		List<DiagnosticInfo> diagnostics
	)
	{
		foreach (
			var property in classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(static p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
		)
		{
			var attributes = property.GetAttributes();
			var propertyType = TypeHelpers.UnwrapNullableType(property.Type);

			var regexAttribute = RegularExpressionAttributeData.FromAttributeData(
				attributes,
				out var regexAttributeData
			);
			if (regexAttribute.Exists)
			{
				if (
					propertyType.SpecialType != SpecialType.System_String
					|| string.IsNullOrEmpty(regexAttribute.Pattern)
				)
				{
					AddUnsupportedDataAnnotationsDiagnostic(
						diagnostics,
						regexAttributeData,
						string.Format(
							CultureInfo.InvariantCulture,
							"RegularExpressionAttribute can only be applied to string properties, but '{0}' is '{1}'.",
							property.Name,
							propertyType.ToDisplayString()
						)
					);
				}
				else
				{
					outputContext.Writer.WriteLine(
						$"static readonly global::System.Text.RegularExpressions.Regex {GetRegexFieldName(property.Name)} = new({CodeGenHelpers.Quote(regexAttribute.Pattern!)}, global::System.Text.RegularExpressions.RegexOptions.CultureInvariant);"
					);
				}
			}

			var rangeAttribute = RangeAttributeData.FromAttributeData(attributes);
			if (
				rangeAttribute.Exists
				&& TryBuildRangeBoundaryExpressions(
					propertyType,
					rangeAttribute,
					out var minimumExpression,
					out var maximumExpression
				)
			)
			{
				var fqTypeName = GetFullyQualifiedTypeName(propertyType);
				outputContext.Writer.WriteLine(
					$"private static readonly {fqTypeName} {GetRangeMinimumFieldName(property.Name)} = {minimumExpression};"
				);
				outputContext.Writer.WriteLine(
					$"private static readonly {fqTypeName} {GetRangeMaximumFieldName(property.Name)} = {maximumExpression};"
				);
			}
		}

		outputContext.Writer.WriteLine();
	}

	static void GenerateValidationHelpers(SchemaGenerationOutputContext outputContext)
	{
		var writer = outputContext.Writer;
		writer.WriteLine(
			$"static void AddError(ref {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError).AsTypeReference().Nullable()} errors, {TypeLibrary.ValidationError} error)"
		);
		using (writer.OpenBlockScope())
		{
			writer.WriteLine(
				$"(errors ??= new {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError)}()).Add(error);"
			);
		}

		using (
			writer.OpenBlockScope(
				$"static void AddNestedErrors<T>(ref {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError).AsTypeReference().Nullable()} errors, {TypeLibrary.ValidationResult}<T> nestedResult, string prefix)"
			)
		)
		{
			using (writer.OpenBlockScope("foreach (var error in nestedResult.Errors)"))
			{
				writer.WriteDelimitedBlock(
					"AddError",
					"(",
					");",
					errorArguments =>
						errorArguments.WriteDelimitedBlock(
							$"ref errors, {TypeLibrary.ValidationError}.Create",
							"(",
							")",
							createArguments =>
							{
								createArguments.WriteLine("error.Code,");
								createArguments.WriteLine("error.Message,");
								createArguments.WriteLine(
									$"{TypeLibrary.Collections.ImmutableArray}.Create(prefix).AddRange(error.Path),"
								);
								createArguments.WriteLine("error.Parameters,");
								createArguments.WriteLine("error.Origin,");
								createArguments.WriteLine("error.Minimum,");
								createArguments.WriteLine("error.Maximum,");
								createArguments.WriteLine("error.Inclusive");
							}
						)
				);
			}
		}

		writer.WriteLine();
		using (
			writer.OpenBlockScope(
				$"static void AddNestedErrors<T>(ref {TypeLibrary.Collections.List.MakeGeneric(TypeLibrary.ValidationError)}? errors, {TypeLibrary.ValidationResult}<T> nestedResult, string prefix, int index)"
			)
		)
		{
			using (writer.OpenBlockScope("foreach (var error in nestedResult.Errors)"))
			{
				writer.WriteLine($"AddError(ref errors, {TypeLibrary.ValidationError}.Create(");
				writer.Indent();
				writer.WriteLine("error.Code,");
				writer.WriteLine("error.Message,");
				writer.WriteLine(
					$"{TypeLibrary.Collections.ImmutableArray}.Create(prefix, index.ToString()).AddRange(error.Path),"
				);
				writer.WriteLine("error.Parameters,");
				writer.WriteLine("error.Origin,");
				writer.WriteLine("error.Minimum,");
				writer.WriteLine("error.Maximum,");
				writer.WriteLine("error.Inclusive");
				writer.Unindent();
				writer.WriteLine("));");
			}
		}

		writer.WriteLine();
		writer.WriteLine("static string FormatCount(int count, string singularNoun, string pluralNoun)");
		using (writer.OpenBlockScope())
		{
			writer.WriteLine("return count == 1 ? $\"1 {singularNoun}\" : $\"{count} {pluralNoun}\";");
		}

		writer.WriteLine();
	}

	static void GenerateParseMethod(SchemaGenerationOutputContext outputContext, string fullTypeName)
	{
		outputContext
			.Writer.XmlSummary("Validates and returns the value, throwing an exception if validation fails.")
			.XmlParam("value", "The value to validate and return.")
			.XmlReturn("The validated value.");
		using (outputContext.Writer.OpenBlockScope($"public static {fullTypeName} Parse({fullTypeName} value)"))
		{
			outputContext.Writer.WriteLine("return Validate(value).GetValueOrThrow();");
		}
	}

	static void GenerateCompositionMethods(
		SchemaGenerationOutputContext outputContext,
		INamedTypeSymbol classSymbol,
		string fullTypeName
	)
	{
		outputContext.Debug($"Generating value-first composition methods for {classSymbol.Name} ({fullTypeName})", 1);

		var validationResultType = TypeLibrary.ValidationResult.MakeGeneric(fullTypeName);

		void WriteFailure(CodeWriter body, string fallbackMessage) =>
			body.WriteDelimitedBlock(
				$"return {validationResultType}.Failure",
				"(",
				");",
				failureArguments =>
					failureArguments.WriteDelimitedBlock(
						$"{TypeLibrary.ValidationError}.Create",
						"(",
						")",
						errorArguments =>
						{
							errorArguments.Quote("validation_failed").WriteLine(",");
							errorArguments.WriteLine($"message ?? \"{fallbackMessage}\",");
							errorArguments.WriteLine("EmptyPath");
						}
					)
			);

		outputContext.Writer.NewLine();

		outputContext.Writer.XmlSummary(
			"Validates the value and then requires an additional predicate to pass (value-first .and()).",
			"Equivalent to Zod's .and() semantics applied to a value."
		);

		outputContext.Writer.WriteBlock(
			$"public static {validationResultType} ApplyAnd("
				+ $"{fullTypeName} value, "
				+ $"global::System.Func<{fullTypeName}, bool> additionalValidation, "
				+ "string? message = null)",
			method =>
			{
				method.WriteLine("var result = Validate(value);");

				method.WriteBlock("if (!result.IsSuccess)", ifBody => ifBody.WriteLine("return result;"));

				method.NewLine();

				method.WriteBlock(
					"if (!additionalValidation(value))",
					ifBody => WriteFailure(ifBody, $"Additional validation failed for {classSymbol.Name}")
				);

				method.NewLine();
				method.WriteLine("return result;");
			}
		);

		outputContext.Writer.NewLine();

		outputContext.Writer.XmlSummary(
			"Validates the value and accepts it if either the schema or an alternative predicate passes (value-first .or()).",
			"Equivalent to Zod's .or() semantics applied to a value."
		);

		outputContext.Writer.WriteBlock(
			$"public static {validationResultType} ApplyOr("
				+ $"{fullTypeName} value, "
				+ $"global::System.Func<{fullTypeName}, bool> alternativeValidation, "
				+ "string? message = null)",
			method =>
			{
				method.WriteLine("var result = Validate(value);");

				method.WriteBlock("if (result.IsSuccess)", ifBody => ifBody.WriteLine("return result;"));

				method.NewLine();

				method.WriteBlock(
					"if (alternativeValidation(value))",
					ifBody => ifBody.WriteLine($"return {validationResultType}.Success(value);")
				);

				method.NewLine();

				WriteFailure(method, $"Neither validation passed for {classSymbol.Name}");
			}
		);

		outputContext.Writer.NewLine();

		outputContext.Writer.XmlSummary(
			"Validates the value and then runs a custom refinement predicate (value-first .refine()).",
			"Equivalent to Zod's .refine() semantics applied to a value."
		);

		outputContext.Writer.WriteBlock(
			$"public static {validationResultType} ApplyRefine("
				+ $"{fullTypeName} value, "
				+ $"global::System.Func<{fullTypeName}, bool> refinement, "
				+ "string? message = null)",
			method =>
			{
				method.WriteLine("var result = Validate(value);");

				method.WriteBlock("if (!result.IsSuccess)", ifBody => ifBody.WriteLine("return result;"));

				method.NewLine();

				method.WriteBlock(
					"if (!refinement(value))",
					ifBody => WriteFailure(ifBody, $"Refinement validation failed for {classSymbol.Name}")
				);

				method.NewLine();
				method.WriteLine("return result;");
			}
		);

		outputContext.Writer.NewLine();
	}
}
