using System.Globalization;
using Microsoft.CodeAnalysis;
using ZodSharp.SourceGenerators.Helpers;
using ZodSharp.SourceGenerators.Models;

namespace ZodSharp.SourceGenerators;

partial class ZodSchemaGenerator
{
	static void BuildSchema(
		SchemaGenerationOutputContext outputContext,
		SourceProductionContext context,
		bool isPrimary
	)
	{
		context.CancellationToken.ThrowIfCancellationRequested();
		var writer = outputContext.Context.CreateCodeWriter();

		GenerateSchemaClass(outputContext, writer, isPrimary, context.CancellationToken);
		context.AddSource($"{outputContext.ZodSchema.SchemaType.Name}.g.cs", writer);

		GenerateRefinementHookDeclaration(outputContext, context);

		context.CancellationToken.ThrowIfCancellationRequested();

		if (!isPrimary || outputContext.ZodSchema.ContainingTypes.Count > 0)
			return;

		// The registration marker advertises a validator that assembly scanning can resolve; without
		// the generated Validate method there is nothing to register.
		if (!outputContext.ZodSchema.GenerateValidateMethod)
			return;

		// The validator type is named here as a typeof rather than left for the consumer to rebuild from a
		// string at runtime. That is what makes RegisterFromAssembly trim- and AOT-safe: the typeof in
		// attribute metadata roots the validator, and the attribute's DynamicallyAccessedMembers annotation
		// keeps its parameterless constructor. The adapter name must match GenerateValidatorAdapter.
		var validatorTypeName =
			$"{outputContext.ZodSchema.SchemaType.Namespace}.{outputContext.ZodSchema.SchemaType.Name}Validator";

		var registrationWriter = outputContext.Context.CreateCodeWriter();
		registrationWriter.AutoGeneratedHeader();
		registrationWriter.Line(
			$"[assembly: global::{TypeLibrary.ZodSharp.Core.ZodSchemaGeneratedAttribute.MetadataFullName}("
				+ $"typeof({outputContext.ZodSchema.TargetType.AsTypeReference()}), "
				+ $"typeof(global::{validatorTypeName}))]"
		);

		context.AddSource($"{outputContext.ZodSchema.SchemaType.Name}Registration.g.cs", registrationWriter);
	}

	/// <summary>
	/// Emits the optional <c>OnZodValidate</c> refinement hook declaration onto the target type, so the IDE
	/// offers the implementation with the generator's signature. Nothing is emitted when the target and its
	/// containing types are not all declared <c>partial</c>.
	/// </summary>
	/// <remarks>
	/// This is the only place the generator writes to a caller-owned type; it mirrors the <c>[ErrorType]</c>
	/// emitter, which also reopens a caller-owned partial class to add generated members.
	/// </remarks>
	static void GenerateRefinementHookDeclaration(
		SchemaGenerationOutputContext outputContext,
		SourceProductionContext context
	)
	{
		var hook = outputContext.ZodSchema.RefinementHook.Value;
		if (!hook.CanEmitDeclaration)
			return;

		var writer = outputContext.Context.CreateCodeWriter();
		writer.AutoGeneratedHeader();

		using (writer.BlockNamespaceScope(outputContext.ZodSchema.TargetType.AsTypeReference()))
		{
			List<CodeWriter.BlockScope> wrapperBlocks = [];

			// The chain is the containing types, outermost first, followed by the target itself.
			for (var index = 0; index < hook.DeclarationChain.Count - 1; index++)
				wrapperBlocks.Add(writer.TypeScope(hook.DeclarationChain[index]));

			writer.Type(
				hook.DeclarationChain[hook.DeclarationChain.Count - 1],
				body => EmitRefinementHook(body, outputContext.ZodSchema)
			);

			foreach (var block in wrapperBlocks)
				block.Dispose();
		}

		context.AddSource($"{outputContext.ZodSchema.SchemaType.Name}.Hooks.g.cs", writer);
	}

	/// <summary>
	/// Writes the partial <c>OnZodValidate</c> declaration the caller implements.
	/// </summary>
	static void EmitRefinementHook(CodeWriter writer, ZodSchemaDescriptor schema)
	{
		var targetType = schema.TargetType.AsTypeReference();
		TypeReference refineContextType = new(
			new TypeIdentity(
				TypeLibraryGenerator.ZodRefineContextName,
				TypeLibraryGenerator.ZodSharpSchemasNamespace,
				1
			).MakeGeneric(targetType)
		);

		writer.XmlSummary(
			"Optional ZodSharp refinement hook. Implement this partial method to add Zod-compatible",
			$"validation rules to {schema.TargetType.Name}.",
			"Issues added to the context are reported by the generated validator: Validate, Parse, the DI",
			"adapter, IValidateOptions, and any factory that validates through the generated schema."
		);
		writer.XmlParam(
			"context",
			"The refinement context carrying the value under validation and the issues it collects."
		);

		writer.PartialMethod(
			new(TypeLibraryGenerator.ZodRefinementHookName) { Parameters = [new("context", refineContextType)] }
		);

		// A classic partial method is private, and the generated schema lives in a different type, so it
		// cannot call the hook directly. This internal bridge keeps the hook optional (an unimplemented
		// partial method elides the call entirely) while giving the schema a call target.
		writer.NewLine();
		writer.XmlSummary(
			"Invokes the optional ZodSharp refinement hook when it is implemented.",
			"Generated for the schema validator to call; not part of the type's own API."
		);
		writer.Method(
			new MethodDeclarationOptions(
				TypeLibraryGenerator.ZodRefinementHookInvokerName,
				TypeDeclarationAccessibility.Internal
			)
			{
				IsStatic = true,
				Parameters = [new("value", targetType), new("context", refineContextType)],
			},
			body => body.MethodCall($"value.{TypeLibraryGenerator.ZodRefinementHookName}", "context")
		);
	}

	static void GenerateSchemaClass(
		SchemaGenerationOutputContext outputContext,
		CodeWriter writer,
		bool isPrimary,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		writer.AutoGeneratedHeader();
		writer
			.Using("System")
			.Using("System.Collections.Generic")
			.Using("System.Collections.Immutable")
			.Using("System.Linq")
			.Using(TypeLibraryGenerator.ZodSharpCoreNamespace)
			.NewLine();

		using (writer.BlockNamespaceScope(outputContext.ZodSchema.TargetType.AsTypeReference()))
		{
			writer.XmlSummary(
				$"Auto-generated schema validator for {CodeWriter.XmlSee(outputContext.ZodSchema.TargetType.Name)}.",
				"This class is generated at compile time for zero-allocation validation."
			);

			List<CodeWriter.BlockScope> wrapperBlocks = [];
			foreach (var containingTypeDeclaration in outputContext.ZodSchema.ContainingTypes)
				wrapperBlocks.Add(writer.TypeScope(containingTypeDeclaration));

			using (
				writer.ClassScope(
					new TypeDeclarationOptions(
						outputContext.ZodSchema.SchemaType,
						outputContext.ZodSchema.TargetAccessibility
					)
					{
						IsPartial = true,
						IsStatic = true,
					}
				)
			)
			{
				writer.Field(
					new FieldDeclarationOptions(
						"EmptyPath",
						TypeLibrary
							.System.Collections.Immutable.ImmutableArray.MakeGeneric(TypeLibrary.System.String)
							.AsTypeReference(),
						TypeDeclarationAccessibility.Private
					)
					{
						IsStatic = true,
						IsReadOnly = true,
						Initializer = "[]",
					}
				);

				GeneratePathFields(writer, outputContext.ZodSchema, cancellationToken);
				GenerateStaticAttributeFields(writer, outputContext.ZodSchema, cancellationToken);

				if (outputContext.ZodSchema.GenerateValidateMethod)
				{
					GenerateValidationHelpers(writer, cancellationToken);

					GenerateValidateMethod(writer, outputContext.ZodSchema, cancellationToken);

					if (outputContext.ZodSchema.GenerateParseMethod)
						GenerateParseMethod(writer, outputContext.ZodSchema, cancellationToken);

					if (outputContext.ZodSchema.EnableComposition)
						GenerateCompositionMethods(writer, outputContext.ZodSchema, cancellationToken);
				}
			}

			if (isPrimary && outputContext.ZodSchema.GenerateValidateMethod)
			{
				GenerateValidatorAdapter(writer, outputContext.ZodSchema, cancellationToken);

				if (
					outputContext.ZodSchema.GenerateIValidateOptions == true
					&& outputContext.Context.Capabilities.HasIValidateOptions
					&& !outputContext.ZodSchema.IsValueType
				)
				{
					GenerateIValidateOptionsValidator(writer, outputContext.ZodSchema, cancellationToken);
				}
			}

			foreach (var block in wrapperBlocks)
				block.Dispose();
		}
	}

	static void GenerateValidatorAdapter(
		CodeWriter writer,
		ZodSchemaDescriptor schema,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var adapterName = $"{schema.SchemaType.Name}Validator";
		var baseType = TypeLibrary.ZodSharp.Core.IZodSchemaValidator.MakeGeneric(schema.TargetType).AsTypeReference();

		writer.XmlSummary(
			$"DI-friendly validator adapter for {schema.TargetType.Name}, delegating to {schema.SchemaType.Name}."
		);

		writer.Class(
			new TypeDeclarationOptions(adapterName)
			{
				Accessibility = schema.TargetAccessibility,
				IsPartial = true,
				BaseType = baseType,
			},
			body =>
			{
				body.XmlSummary("Validates an instance of the target type, returning a ValidationResult.")
					.XmlParam("value", "The value to validate.")
					.XmlReturn("ValidationResult indicating success or failure of the validation.")
					.Method(
						new MethodDeclarationOptions(
							"Validate",
							TypeLibrary.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType).AsTypeReference(),
							TypeDeclarationAccessibility.Public
						)
						{
							Parameters =
							[
								new ParameterDeclarationOptions("value", schema.TargetType.AsTypeReference()),
							],
						},
						methodBody => methodBody.Return($"{schema.SchemaType.Name}.Validate(value)")
					);

				GenerateValidateAsyncMethod(body, schema, cancellationToken);
			}
		);
	}

	static void GenerateIValidateOptionsValidator(
		CodeWriter writer,
		ZodSchemaDescriptor schema,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var validatorName = $"{schema.TargetType.Name}Validator";
		var targetType = schema.TargetType.AsTypeReference();
		var baseType = TypeLibrary
			.Microsoft.Extensions.Options.IValidateOptions.MakeGeneric(schema.TargetType)
			.AsTypeReference();
		var validateOptionsResult = TypeLibrary.Microsoft.Extensions.Options.ValidateOptionsResult.AsTypeReference();
		var nullableString = PurviewTypeLibrary.System.String.AsTypeReference().Nullable(writer);

		writer.XmlSummary(
			$"Validates {CodeWriter.XmlSee(schema.TargetType.Name)} via the source-generated schema, for use with Microsoft.Extensions.Options."
		);

		writer.Class(
			new TypeDeclarationOptions(validatorName)
			{
				Accessibility = schema.TargetAccessibility,
				IsSealed = true,
				BaseType = baseType,
			},
			body =>
				body.XmlSummary("Validates the options instance against the source-generated schema.")
					.XmlParam("name", "The options name (unused by schema validation).")
					.XmlParam("options", "The options instance to validate.")
					.XmlReturn("A ValidateOptionsResult indicating success or the validation failure messages.")
					.Method(
						new MethodDeclarationOptions(
							"Validate",
							validateOptionsResult,
							TypeDeclarationAccessibility.Public
						)
						{
							Parameters =
							[
								new ParameterDeclarationOptions("name", nullableString),
								new ParameterDeclarationOptions("options", targetType),
							],
						},
						method =>
						{
							method.Assignment("var", "schemaResult", $"{schema.SchemaType.Name}.Validate(options)");
							method.IfBlock(
								"schemaResult.IsSuccess",
								ifBody => ifBody.Return($"{validateOptionsResult}.Success")
							);
							method.NewLine();
							method.Return(
								$"{validateOptionsResult}.Fail(schemaResult.Errors.Select(static error => error.Message))"
							);
						}
					)
		);

		writer.NewLine();
	}

	static void GenerateValidateAsyncMethod(
		CodeWriter writer,
		ZodSchemaDescriptor schema,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var customValidation = schema.CustomValidationMethod.Value;
		var returnType = TypeLibraryGenerator
			.ValueTask.MakeGeneric(TypeLibrary.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType))
			.AsTypeReference();
		var valueType = schema.TargetType.AsTypeReference();
		var cancellationTokenType = TypeLibraryGenerator.CancellationToken.AsTypeReference();

		MethodDeclarationOptions methodDeclaration = new(
			"ValidateAsync",
			returnType,
			TypeDeclarationAccessibility.Public
		)
		{
			IsAsync = customValidation.InvocationKind != CustomValidationInvocationKind.None,
			Parameters =
			[
				new ParameterDeclarationOptions("value", valueType),
				new ParameterDeclarationOptions("cancellationToken", cancellationTokenType)
				{
					DefaultValue = "default",
				},
			],
		};

		writer
			.XmlSummary("Asynchronously validates an instance of the target type, returning a ValidationResult.")
			.XmlParam("value", "The value to validate.")
			.XmlParam("cancellationToken", "The cancellation token.")
			.XmlReturn("ValidationResult indicating success or failure of the validation.")
			.Method(
				methodDeclaration,
				method =>
				{
					if (customValidation.InvocationKind == CustomValidationInvocationKind.None)
					{
						method.Return(
							$"global::System.Threading.Tasks.ValueTask.FromResult({schema.SchemaType.Name}.Validate(value))"
						);
						return;
					}

					method.Assignment("var", "syncResult", $"{schema.SchemaType.Name}.Validate(value)");

					var prefix =
						customValidation.InvocationKind == CustomValidationInvocationKind.DefinedOnSchemaValidator
							? "this."
							: $"{schema.TargetType}.";

					method.Assignment(
						"var",
						"customResult",
						$"await {prefix}{customValidation.MethodName}(value, cancellationToken).ConfigureAwait(false)"
					);

					method.NewLine();
					method.Return(
						$"{TypeLibrary.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType)}.Merge(syncResult, customResult)"
					);
				}
			);
	}

	static void GenerateValidateMethod(
		CodeWriter writer,
		ZodSchemaDescriptor schema,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		writer.XmlSummary("Validates an instance of the target type.");
		MethodDeclarationOptions methodDeclaration = new(
			"Validate",
			TypeLibrary.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType).AsTypeReference(),
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters = [new ParameterDeclarationOptions("value", schema.TargetType.AsTypeReference())],
		};

		writer.Method(
			methodDeclaration,
			method =>
			{
				if (schema.TargetCanBeNull)
				{
					method.IfBlock(
						"value is null",
						ifBody =>
							ifBody.Return(
								$"{TypeLibrary.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType)}.Failure({TypeLibrary.ZodSharp.Core.ValidationError}.Create({"invalid_type".Surround()}, {"Value cannot be null".Surround()}, EmptyPath))"
							)
					);
				}

				var errorsListType = TypeLibrary
					.System.Collections.Generic.List.MakeGeneric(TypeLibrary.ZodSharp.Core.ValidationError)
					.AsTypeReference()
					.Nullable(method);

				method.NewLine().Assignment(errorsListType, "errors", "null");

				foreach (var property in schema.Properties)
				{
					if (property.ShouldProcess)
						GeneratePropertyValidation(
							writer,
							property.Value,
							schema.ValidateEnumValues,
							cancellationToken
						);
				}

				GenerateTypeRuleValidations(writer, schema);

				GenerateZodRefinement(schema, method);

				method.IfBlock(
					"errors is not null",
					ifBody =>
						ifBody.Return(
							TypeLibrary
								.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType)
								.StaticMember("Failure(errors)")
						)
				);

				method
					.Line()
					.Return(
						TypeLibrary
							.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType)
							.StaticMember("Success(value)")
					);
			}
		);

		writer.NewLine();
	}

	static void GenerateZodRefinement(ZodSchemaDescriptor schema, CodeWriter method)
	{
		var hook = schema.RefinementHook.Value;
		if (!hook.IsImplemented)
			return;

		// The hook runs after the attribute and type rules, so its issues merge into the same error set
		// the generated Validate returns. Nothing is emitted when the target supplies no body, so a type
		// that only leaves the generated declaration in place stays on the zero-allocation path.
		method.Line();
		method.Assignment(
			$"global::{TypeLibraryGenerator.ZodSharpSchemasNamespace}.RefineCtx<{schema.TargetType.AsTypeReference()}>",
			"refineContext",
			"new(value, EmptyPath)"
		);
		method.MethodCall(
			$"{schema.TargetType.AsTypeReference()}.{TypeLibraryGenerator.ZodRefinementHookInvokerName}",
			"value",
			"refineContext"
		);
		using (method.IfBlockScope("refineContext.HasIssues"))
		{
			method.Foreach(
				"var refinementIssue in refineContext.Issues",
				foreachBody => foreachBody.MethodCall("AddError", "ref errors", "refinementIssue")
			);
		}

		method.NewLine();
	}

	static void GenerateParseMethod(CodeWriter writer, ZodSchemaDescriptor schema, CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();

		writer
			.XmlSummary("Validates and returns the value, throwing an exception if validation fails.")
			.XmlParam("value", "The value to validate and return.")
			.XmlReturn("The validated value.");

		MethodDeclarationOptions methodDeclaration = new(
			"Parse",
			schema.TargetType.AsTypeReference(),
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters = [new("value", schema.TargetType.AsTypeReference())],
		};

		writer.Method(methodDeclaration, methodBody => methodBody.Return("Validate(value).GetValueOrThrow()"));
	}

	static void GenerateCompositionMethods(
		CodeWriter writer,
		ZodSchemaDescriptor schema,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var validationResultType = TypeLibrary
			.ZodSharp.Core.ValidationResult.MakeGeneric(schema.TargetType)
			.AsTypeReference();
		var targetType = schema.TargetType.AsTypeReference();
		var funcType = PurviewTypeLibrary
			.System.Func.WithArity(2)
			.MakeGeneric(schema.TargetType, PurviewTypeLibrary.System.Boolean)
			.AsTypeReference();
		var stringType = PurviewTypeLibrary.System.String.MakeNullable(writer);

		void WriteFailure(CodeWriter body, string fallbackMessage) =>
			body.Return(
				$"{validationResultType}.Failure({TypeLibrary.ZodSharp.Core.ValidationError}.Create({"validation_failed".Surround()}, message ?? {fallbackMessage.Surround()}, EmptyPath))"
			);

		writer
			.Line()
			.XmlSummary(
				"Validates the value and then requires an additional predicate to pass (value-first .and()).",
				"Equivalent to Zod's .and() semantics applied to a value."
			)
			.Method(
				new("ApplyAnd", validationResultType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters =
					[
						new("value", targetType),
						new("additionalValidation", funcType),
						new("message", stringType) { DefaultValue = "null" },
					],
				},
				method =>
				{
					method.Assignment("var", "result", "Validate(value)");

					method.IfBlock("!result.IsSuccess", ifBody => ifBody.Return("result"));
					method.NewLine();
					method.IfBlock(
						"!additionalValidation(value)",
						ifBody => WriteFailure(ifBody, $"Additional validation failed for {schema.TargetType.Name}")
					);
					method.NewLine();
					method.Return("result");
				}
			);

		writer.NewLine();
		writer
			.XmlSummary(
				"Validates the value and accepts it if either the schema or an alternative predicate passes (value-first .or()).",
				"Equivalent to Zod's .or() semantics applied to a value."
			)
			.Method(
				new MethodDeclarationOptions("ApplyOr", validationResultType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters =
					[
						new("value", targetType),
						new("alternativeValidation", funcType),
						new("message", stringType) { DefaultValue = "null" },
					],
				},
				method =>
				{
					method.Assignment("var", "result", "Validate(value)");
					method.IfBlock("result.IsSuccess", ifBody => ifBody.Return("result"));
					method.NewLine();
					method.IfBlock(
						"alternativeValidation(value)",
						ifBody => ifBody.Return($"{validationResultType}.Success(value)")
					);
					method.NewLine();
					WriteFailure(method, $"Neither validation passed for {schema.TargetType.Name}");
				}
			);

		writer.NewLine();
		writer
			.XmlSummary(
				"Validates the value and then runs a custom refinement predicate (value-first .refine()).",
				"Equivalent to Zod's .refine() semantics applied to a value."
			)
			.Method(
				new("ApplyRefine", validationResultType, TypeDeclarationAccessibility.Public)
				{
					IsStatic = true,
					Parameters =
					[
						new("value", targetType),
						new("refinement", funcType),
						new("message", stringType) { DefaultValue = "null" },
					],
				},
				method =>
				{
					method.Assignment("var", "result", "Validate(value)");
					method.IfBlock("!result.IsSuccess", ifBody => ifBody.Return("result"));
					method.NewLine();
					method.IfBlock(
						"!refinement(value)",
						ifBody => WriteFailure(ifBody, $"Refinement validation failed for {schema.TargetType.Name}")
					);
					method.NewLine();
					method.Return("result");
				}
			);

		writer.NewLine();
	}

	static void GeneratePropertyValidation(
		CodeWriter writer,
		ZodPropertyDescriptor property,
		bool validateEnumValues,
		CancellationToken cancellationToken
	)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var propertyName = property.Name;
		var displayName = property.DisplayName;
		var attributes = property.ValidationAttributes;
		CodeWriter.BlockScope? block = null;

		// The enum rule owns the property's value set: the values a [DeniedValues] attribute lists are
		// absorbed into the rule's disallowed set, so the standalone denied-values validation is skipped.
		var emitEnumRule = IsEnumValidationEmitted(property, validateEnumValues);

		// A rule that rejects an absent value (IRequiredRule) stands in for [Required]: it is emitted outside
		// the non-null guard, so a missing value fails instead of being skipped.
		var hasRequiredRule = TryGetRequiredRule(property, out var requiredRule);

		if (property.CanBeNull && attributes.Required.ShouldProcess && attributes.Required.Value.Exists)
		{
			var required = attributes.Required.Value;
			var isStringAndAllowEmptyStrings =
				property.PropertyType.SpecialType == SpecialType.System_String && required.AllowEmptyStrings;
			var localErrorMessage = isStringAndAllowEmptyStrings
				? "Field '{0}' is required and cannot be null or empty"
				: "Required field '{0}' is null";
			var errorMessage = string.Format(
				CultureInfo.InvariantCulture,
				required.ValidationAttribute.ErrorMessage ?? localErrorMessage,
				displayName
			);
			var comparison = isStringAndAllowEmptyStrings
				? $"string.IsNullOrEmpty(value.{propertyName})"
				: $"value.{propertyName} == null";

			writer.Rule(propertyName, comparison, "missing_field", errorMessage);
			block = writer.ElseScope();
			GenerateValueSetValidations(writer, property, emitEnumRule);
		}
		else if (hasRequiredRule)
		{
			GenerateRequiredRuleValidation(writer, property, requiredRule);
			block = writer.ElseScope();
			GenerateValueSetValidations(writer, property, emitEnumRule);
		}
		else
		{
			GenerateValueSetValidations(writer, property, emitEnumRule);
			if (property.CanBeNull)
				block = writer.IfBlockScope($"value.{propertyName} != null");
		}

		GenerateTypeSpecificValidations(writer, property, emitEnumRule, skipRequiredRule: hasRequiredRule);
		block?.Dispose();

		GenerateCompareValidation(writer, property);
		writer.NewLine();
	}

	/// <summary>
	/// Finds the rule that rejects an absent value (<c>IRequiredRule</c>) among the property's custom rules,
	/// when the property can be null.
	/// </summary>
	/// <param name="property">The property to inspect.</param>
	/// <param name="requiredRule">The required rule, when one is bound to the property.</param>
	/// <returns><see langword="true"/> when a required rule is bound to a nullable property.</returns>
	static bool TryGetRequiredRule(ZodPropertyDescriptor property, out CustomRuleDescriptor requiredRule)
	{
		requiredRule = default;

		if (!property.CanBeNull)
			return false;

		foreach (var rule in property.CustomRules)
		{
			if (!rule.IsRequired)
				continue;

			requiredRule = rule;
			return true;
		}

		return false;
	}

	static void GenerateTypeSpecificValidations(
		CodeWriter writer,
		ZodPropertyDescriptor property,
		bool emitEnumRule,
		bool skipRequiredRule
	)
	{
		switch (property.ValidationKind)
		{
			case PropertyValidationKind.String:
				GenerateStringValidations(writer, property);
				break;
			case PropertyValidationKind.Numeric:
			case PropertyValidationKind.Comparable:
				GenerateRangeValidations(writer, property);
				break;
			case PropertyValidationKind.Collection:
				GenerateCollectionValidations(writer, property);
				break;
			case PropertyValidationKind.Complex:
				GenerateComplexTypeValidation(writer, property);
				break;
			case PropertyValidationKind.Enum:
				if (emitEnumRule)
					GenerateEnumValidation(writer, property);
				break;
			case PropertyValidationKind.Unsupported:
				break;
			default:
				break;
		}

		GenerateCustomRuleValidations(writer, property, skipRequiredRule);
	}

	static void GenerateCompareValidation(CodeWriter writer, ZodPropertyDescriptor property)
	{
		var compareAttribute = property.ValidationAttributes.Compare;
		if (!compareAttribute.ShouldProcess || !compareAttribute.Value.Exists)
			return;

		var compare = compareAttribute.Value;
		var displayName = property.DisplayName;
		var otherDisplayName = compare.OtherPropertyDisplayName ?? compare.OtherProperty;

		var messageExpression = BuildErrorMessageExpression(
			compare.ValidationAttribute,
			"Field '{0}' must match '{1}'.",
			displayName.StringLiteral(),
			otherDisplayName.StringLiteral()
		);

		writer.IfBlock(
			$"!global::System.Collections.Generic.EqualityComparer<object>.Default.Equals(value.{property.Name}, value.{compare.OtherProperty})",
			ifBody =>
				WriteValidationError(
					ifBody,
					"mismatch",
					messageExpression,
					CodeGenHelpers.GetPathFieldName(property.Name)
				)
		);

		writer.NewLine();
	}

	static void GenerateCollectionElementValidation(CodeWriter writer, ZodPropertyDescriptor property)
	{
		if (property.NestedSchemaType is null)
			return;

		var propertyName = property.Name;
		var collectionValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Collection");
		var itemValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Item");
		var itemResultName = CodeGenHelpers.GetLocalIdentifier(propertyName, "ItemResult");
		var indexName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Index");
		var schemaType = property.NestedSchemaType.Value;

		writer.Assignment("var", collectionValueName, $"value.{propertyName}");
		using (writer.IfBlockScope($"{collectionValueName} is not null"))
		{
			writer.Assignment("var", indexName, "0");
			using (writer.ForeachScope($"var {itemValueName} in {collectionValueName}"))
			{
				if (property.ElementTypeCanBeNull)
				{
					writer.IfBlock(
						$"{itemValueName} is null",
						ifBody =>
						{
							ifBody.Line($"{indexName}++;");
							ifBody.Line("continue;");
						}
					);
				}

				writer.Assignment("var", itemResultName, schemaType.StaticMember($"Validate({itemValueName})"));
				using (writer.IfBlockScope($"!{itemResultName}.IsSuccess"))
				{
					writer.MethodCall(
						"AddNestedErrors",
						"ref errors",
						itemResultName,
						propertyName.Surround(),
						indexName
					);
				}

				writer.Line($"{indexName}++;");
			}
		}

		writer.NewLine();
	}

	static void GenerateComplexTypeValidation(CodeWriter writer, ZodPropertyDescriptor property)
	{
		if (property.NestedSchemaType is null)
			return;

		var propertyName = property.Name;
		var propertyValueName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Value");
		var nestedResultName = CodeGenHelpers.GetLocalIdentifier(propertyName, "Result");
		var schemaType = property.NestedSchemaType.Value;

		writer.Assignment("var", propertyValueName, $"value.{propertyName}");
		if (property.CanBeNull)
		{
			using (writer.IfBlockScope($"{propertyValueName} is not null"))
			{
				writer.Assignment("var", nestedResultName, $"{schemaType}.Validate({propertyValueName})");
				using (writer.IfBlockScope($"!{nestedResultName}.IsSuccess"))
				{
					writer.MethodCall("AddNestedErrors", "ref errors", nestedResultName, propertyName.Surround());
				}
			}
		}
		else
		{
			writer.Assignment("var", nestedResultName, $"{schemaType}.Validate({propertyValueName})");
			using (writer.IfBlockScope($"!{nestedResultName}.IsSuccess"))
			{
				writer.MethodCall("AddNestedErrors", "ref errors", nestedResultName, propertyName.Surround());
			}
		}
	}

	static void GeneratePathFields(CodeWriter writer, ZodSchemaDescriptor schema, CancellationToken cancellationToken)
	{
		var pathFieldType = TypeLibrary.System.Collections.Immutable.ImmutableArray.MakeGeneric(
			TypeLibrary.System.String
		);

		foreach (var property in schema.Properties)
		{
			cancellationToken.ThrowIfCancellationRequested();
			if (!property.ShouldProcess)
				continue;

			writer.Field(
				new(
					CodeGenHelpers.GetPathFieldName(property.Value.Name),
					pathFieldType,
					TypeDeclarationAccessibility.Private
				)
				{
					IsStatic = true,
					IsReadOnly = true,
					Initializer = new TypeIdentity(typeof(System.Collections.Immutable.ImmutableArray)).StaticMember(
						$"Create({property.Value.Name.Surround()})"
					),
				}
			);
		}
	}

	static void GenerateStaticAttributeFields(
		CodeWriter writer,
		ZodSchemaDescriptor schema,
		CancellationToken cancellationToken
	)
	{
		var regexType = new TypeIdentity("Regex", "System.Text.RegularExpressions").AsTypeReference();

		foreach (var property in schema.Properties)
		{
			cancellationToken.ThrowIfCancellationRequested();
			if (!property.ShouldProcess)
				continue;

			var prop = property.Value;

			if (prop.ValidationAttributes.RegularExpression.ShouldProcess)
			{
				var pattern = prop.ValidationAttributes.RegularExpression.Value.Pattern ?? string.Empty;
				writer.Field(
					new(GetRegexFieldName(prop.Name), regexType, TypeDeclarationAccessibility.Private)
					{
						IsStatic = true,
						IsReadOnly = true,
						// The pattern is author-supplied but runs against untrusted request input, so it
						// carries the same match timeout RegexRule applies to string patterns. Without
						// it a catastrophically backtracking pattern hangs the request thread; note
						// RegularExpressionAttribute, which this mirrors, defaults to a 2s timeout.
						Initializer =
							$"new({pattern.StringLiteral()}, global::System.Text.RegularExpressions.RegexOptions.CultureInvariant, global::ZodSharp.Rules.RegexRule.DefaultMatchTimeout)",
					}
				);
			}

			if (prop.ValidationAttributes.Range.ShouldProcess)
			{
				var propertyType = prop.PropertyType.AsTypeReference();
				var range = prop.ValidationAttributes.Range.Value;
				writer.Field(
					new(GetRangeMinimumFieldName(prop.Name), propertyType, TypeDeclarationAccessibility.Private)
					{
						IsStatic = true,
						IsReadOnly = true,
						Initializer = range.MinimumExpression,
					}
				);
				writer.Field(
					new(GetRangeMaximumFieldName(prop.Name), propertyType, TypeDeclarationAccessibility.Private)
					{
						IsStatic = true,
						IsReadOnly = true,
						Initializer = range.MaximumExpression,
					}
				);
			}
		}

		writer.NewLine();
	}

	static void GenerateValidationHelpers(CodeWriter writer, CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();

		var listOfErrorsType = TypeLibrary.System.Collections.Generic.List.MakeGeneric(
			TypeLibrary.ZodSharp.Core.ValidationError
		);
		var errorType = TypeLibrary.ZodSharp.Core.ValidationError.AsTypeReference();
		TypeIdentity immutableArrayType = new(typeof(System.Collections.Immutable.ImmutableArray));
		var typeParameterT = new TypeIdentity("T", null).AsTypeReference();

		writer.Method(
			new("AddError", TypeDeclarationAccessibility.Private)
			{
				IsStatic = true,
				Parameters =
				[
					new("errors", listOfErrorsType.MakeNullable(writer)) { Modifier = ParameterModifier.Ref },
					new("error", errorType),
				],
			},
			body => body.MethodCallOn($"(errors ??= new {listOfErrorsType}())", "Add", "error")
		);

		writer.Method(
			new("AddNestedErrors", TypeDeclarationAccessibility.Private)
			{
				IsStatic = true,
				GenericTypes = [new GenericTypeParameterOptions("T")],
				Parameters =
				[
					new("errors", listOfErrorsType.MakeNullable(writer)) { Modifier = ParameterModifier.Ref },
					new(
						"nestedResult",
						TypeLibrary.ZodSharp.Core.ValidationResult.MakeGeneric(typeParameterT).AsTypeReference()
					),
					new("prefix", new TypeIdentity(SpecialType.System_String).AsTypeReference()),
				],
			},
			body =>
				body.Foreach(
					"var error in nestedResult.Errors",
					foreachBody =>
						foreachBody.MethodCall(
							"AddError",
							"ref errors",
							$"{TypeLibrary.ZodSharp.Core.ValidationError}.Create(error.Code, error.Message, {immutableArrayType}.Create(prefix).AddRange(error.Path), error.Parameters, error.Origin, error.Minimum, error.Maximum, error.Inclusive, error.Category)"
						)
				)
		);

		writer.Method(
			new("AddNestedErrors", TypeDeclarationAccessibility.Private)
			{
				IsStatic = true,
				GenericTypes = [new GenericTypeParameterOptions("T")],
				Parameters =
				[
					new("errors", listOfErrorsType.MakeNullable(writer)) { Modifier = ParameterModifier.Ref },
					new(
						"nestedResult",
						TypeLibrary.ZodSharp.Core.ValidationResult.MakeGeneric(typeParameterT).AsTypeReference()
					),
					new("prefix", new TypeIdentity(SpecialType.System_String).AsTypeReference()),
					new("index", new TypeIdentity(SpecialType.System_Int32).AsTypeReference()),
				],
			},
			body =>
				body.Foreach(
					"var error in nestedResult.Errors",
					foreachBody =>
						foreachBody.MethodCall(
							"AddError",
							"ref errors",
							$"{TypeLibrary.ZodSharp.Core.ValidationError}.Create(error.Code, error.Message, {immutableArrayType}.Create(prefix, index.ToString()).AddRange(error.Path), error.Parameters, error.Origin, error.Minimum, error.Maximum, error.Inclusive, error.Category)"
						)
				)
		);

		writer.NewLine();
		writer.Method(
			new(
				"FormatCount",
				new TypeIdentity(SpecialType.System_String).AsTypeReference(),
				TypeDeclarationAccessibility.Private
			)
			{
				IsStatic = true,
				Parameters =
				[
					new("count", new TypeIdentity(SpecialType.System_Int32).AsTypeReference()),
					new("singularNoun", new TypeIdentity(SpecialType.System_String).AsTypeReference()),
					new("pluralNoun", new TypeIdentity(SpecialType.System_String).AsTypeReference()),
				],
			},
			body => body.Return("count == 1 ? $\"1 {singularNoun}\" : $\"{count} {pluralNoun}\"")
		);

		writer.NewLine();
	}
}
