using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZodSharp.SourceGenerators.Helpers;
using ZodSharp.SourceGenerators.Helpers.Models;
using ExecutionContext = ZodSharp.SourceGenerators.Helpers.Models.ExecutionContext;

namespace ZodSharp.SourceGenerators;

partial class ZodSchemaGenerator
{
	static void Execute(
		TargetSymbolDescriptor targetDescriptor,
		ExecutionContext executionContext,
		SourceProductionContext context
	)
	{
		try
		{
			using (executionContext.Writer.Begin())
			{
				List<Diagnostic> diagnostics = [];
				var source = GenerateSchemaClass(targetDescriptor.Symbol, executionContext, diagnostics);
				if (diagnostics.Count > 0)
					ReportDiagnostics(context, diagnostics, executionContext);

				var fileName = $"{targetDescriptor.Symbol.Name}Schema.g.cs";
				context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
			}
		}
		catch (Exception ex)
		{
			// Report diagnostic if generation fails
			var diagnostic = Diagnostic.Create(
				GeneratorDiagnostics.UnhandledException,
				targetDescriptor.Declaration.GetLocation(),
				targetDescriptor.Symbol.Name,
				ex.Message
			);

			ReportDiagnostics(context, diagnostic, executionContext);
		}
	}

	static string GenerateSchemaClass(
		INamedTypeSymbol classSymbol,
		ExecutionContext executionContext,
		List<Diagnostic> diagnostics
	)
	{
		var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
		var className = classSymbol.Name;
		var schemaName = $"{className}Schema";
		var fullTypeName = classSymbol.ToDisplayString();
		var modifier = TypeHelpers.GetLimitedAccessibilityKeyword(classSymbol);

		executionContext.Logger?.Info(
			$"Generating schema {schemaName} ({modifier}) for {className} in namespace {namespaceName}"
		);

		// Estimate capacity based on number of properties
		var propertyCount = classSymbol
			.GetMembers()
			.OfType<IPropertySymbol>()
			.Count(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

		executionContext.Logger?.Info($"Property count for {className}: {propertyCount}", 1);

		executionContext.Writer.WriteLine("// <auto-generated />");
		executionContext.Writer.WriteLine();
		executionContext.Writer.WriteLine("using System;");
		executionContext.Writer.WriteLine("using System.Collections.Generic;");
		executionContext.Writer.WriteLine("using System.Collections.Immutable;");

		executionContext.Writer.WriteLine("using ZodSharp.Core;");
		executionContext.Writer.WriteLine();

		executionContext.Writer.WriteLine($"namespace {namespaceName};");
		executionContext.Writer.WriteLine();
		executionContext.Writer.WriteLine("#nullable enable");
		executionContext.Writer.WriteLine();
		executionContext.Writer.WriteLine("/// <summary>");
		executionContext.Writer.WriteLine($"/// Auto-generated schema validator for {className}.");
		executionContext.Writer.WriteLine(
			"/// This class is generated at compile time for zero-allocation validation."
		);
		executionContext.Writer.WriteLine("/// </summary>");
		executionContext.Writer.WriteLine("{{CodeGen}}");

		using (executionContext.Writer.Block($"{modifier} static partial class {schemaName}"))
		{
			executionContext.Writer.WriteLine(
				$"static readonly {TypeHelpers.ImmutableArrayMetadataName.Global()}<string> EmptyPath = {TypeHelpers.ImmutableArrayMetadataName.Global()}<string>.Empty;"
			);
			executionContext.Writer.WriteLine();
			GeneratePathFields(executionContext, classSymbol);
			GenerateStaticAttributeFields(executionContext, classSymbol, diagnostics);
			GenerateValidationHelpers(executionContext);

			GenerateValidateMethod(executionContext, classSymbol, fullTypeName, diagnostics);
			GenerateParseMethod(executionContext, fullTypeName);
		}

		return CodeGenHelpers.ProcessGeneratedCode(executionContext.Writer.ToString());
	}

	static void GenerateValidateMethod(
		ExecutionContext executionContext,
		INamedTypeSymbol classSymbol,
		string fullTypeName,
		List<Diagnostic> diagnostics
	)
	{
		var writer = executionContext.Writer;
		writer.WriteLine("/// <summary>");
		writer.WriteLine("/// Validates an instance of the target type.");
		writer.WriteLine("/// </summary>");
		writer.WriteLine(
			$"public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> Validate({fullTypeName} value)"
		);

		using (writer.Block())
		{
			if (TypeHelpers.CanBeNull(classSymbol))
			{
				using (writer.Block("if (value == null)"))
				{
					using (
						writer.Block(
							$"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure",
							seperator: "(",
							closingSeperator: ");"
						)
					)
					{
						using (writer.Block($"{TypeHelpers.ValidationError.Global()}.Create", seperator: "("))
						{
							writer.WriteIndent().Quote("invalid_type").Write(",").NewLine();
							writer.WriteIndent().Quote("Value cannot be null").Write(",").NewLine();
							writer.WriteIndent().Write("EmptyPath").NewLine();
						}
					}
				}

				writer.NewLine();
			}

			writer.WriteLine(
				$"{typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>? errors = null;"
			);

			var properties = classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
				.ToList();

			foreach (var property in properties)
				GeneratePropertyValidation(executionContext, property, diagnostics);

			using (writer.Block("if (errors is not null)"))
			{
				writer.WriteLine($"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(errors);");
			}

			writer
				.WriteLine()
				.WriteLine($"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Success(value);");
		}
	}

	static void GeneratePropertyValidation(
		ExecutionContext executionContext,
		IPropertySymbol property,
		List<Diagnostic> diagnostics
	)
	{
		var propertyName = property.Name;
		var propertyType = property.Type
			is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullableType
			? nullableType.TypeArguments[0]
			: property.Type;
		var canBeNull = TypeHelpers.CanBeNull(property.Type);

		var attributes = property.GetAttributes();
		var requiredAttrib = RequiredAttributeData.FromAttributeData(executionContext, attributes);

		IDisposable? block = null;
		if (canBeNull && requiredAttrib.Exists)
		{
			var isStringAndAllowEmptyStrings =
				propertyType.SpecialType == SpecialType.System_String && requiredAttrib.AllowEmptyStrings;
			var localErrorMessage = isStringAndAllowEmptyStrings
				? "Field '{0}' is required and cannot be null or empty"
				: "Required field '{0}' is null";

			var errorMessage = string.Format(
				CultureInfo.InvariantCulture,
				requiredAttrib.ErrorMessage ?? localErrorMessage,
				propertyName
			);

			var comparision = isStringAndAllowEmptyStrings
				? $"string.IsNullOrEmpty(value.{propertyName})"
				: $"value.{propertyName} == null";

			executionContext.Writer.WriteRule(propertyName, comparision, "missing_field", errorMessage);

			block = executionContext.Writer.Block("else");
			GenerateValueSetValidations(
				executionContext,
				property,
				property.Type,
				propertyName,
				attributes,
				diagnostics
			);
		}
		else
		{
			GenerateValueSetValidations(
				executionContext,
				property,
				property.Type,
				propertyName,
				attributes,
				diagnostics
			);

			if (canBeNull)
				block = executionContext.Writer.Block($"if (value.{propertyName} != null)");
		}

		GenerateTypeSpecificValidations(
			executionContext,
			property,
			propertyType,
			attributes,
			propertyName,
			diagnostics
		);

		block?.Dispose();

		executionContext.Writer.WriteLine();
	}

	static void GenerateTypeSpecificValidations(
		ExecutionContext executionContext,
		IPropertySymbol property,
		ITypeSymbol propertyType,
		ImmutableArray<AttributeData> attributes,
		string propertyName,
		List<Diagnostic> diagnostics
	)
	{
		var lengthAttributeData = FindAttribute(attributes, executionContext.LengthAttribute);
		var supportsLengthAttribute =
			propertyType.SpecialType == SpecialType.System_String
			|| propertyType is IArrayTypeSymbol
			|| TypeHelpers.ImplementsInterface(propertyType, executionContext.IEnumerable)
			|| TypeHelpers.ImplementsInterface(propertyType, executionContext.IEnumerableOfT);

		if (lengthAttributeData is not null && !supportsLengthAttribute)
			AddUnsupportedLengthTargetDiagnostic(diagnostics, lengthAttributeData, propertyName, propertyType);

		var rangeAttributeData = FindAttribute(attributes, executionContext.RangeAttribute);
		if (
			rangeAttributeData is not null
			&& !TryBuildRangeBoundaryExpressions(
				propertyType,
				RangeAttributeData.FromAttributeData(executionContext, rangeAttributeData),
				out _,
				out _
			)
		)
		{
			AddUnsupportedDataAnnotationsDiagnostic(
				diagnostics,
				rangeAttributeData,
				string.Format(
					CultureInfo.InvariantCulture,
					"RangeAttribute on '{0}' cannot be generated safely for '{1}'.",
					propertyName,
					propertyType.ToDisplayString()
				)
			);
		}

		if (propertyType.SpecialType == SpecialType.System_String)
		{
			GenerateStringValidations(executionContext, property, propertyName, attributes, diagnostics);
		}
		else if (TypeHelpers.IsNumericType(propertyType))
		{
			GenerateNumericValidations(executionContext, property, propertyType, propertyName, attributes, diagnostics);
		}
		else if (
			propertyType is IArrayTypeSymbol
			|| TypeHelpers.ImplementsInterface(propertyType, executionContext.IEnumerable)
			|| TypeHelpers.ImplementsInterface(propertyType, executionContext.IEnumerableOfT)
		)
		{
			GenerateCollectionValidations(
				executionContext,
				property,
				propertyType,
				propertyName,
				attributes,
				diagnostics
			);
		}
	}

	static void GeneratePathFields(ExecutionContext executionContext, INamedTypeSymbol classSymbol)
	{
		foreach (
			var property in classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
		)
		{
			executionContext.Writer.WriteLine(
				$"static readonly {TypeHelpers.ImmutableArrayMetadataName.Global()}<string> {GetPathFieldName(property.Name)} = {TypeHelpers.ImmutableArrayMetadataName.Global()}.Create({Quote(property.Name)});"
			);
		}

		executionContext.Writer.WriteLine();
	}

	static void GenerateStaticAttributeFields(
		ExecutionContext executionContext,
		INamedTypeSymbol classSymbol,
		List<Diagnostic> diagnostics
	)
	{
		foreach (
			var property in classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
		)
		{
			var attributes = property.GetAttributes();
			var propertyType = TypeHelpers.UnwrapNullableType(property.Type);

			var regexAttribute = RegularExpressionAttributeData.FromAttributeData(executionContext, attributes);
			if (regexAttribute.Exists)
			{
				if (
					propertyType.SpecialType != SpecialType.System_String
					|| string.IsNullOrEmpty(regexAttribute.Pattern)
				)
				{
					AddUnsupportedDataAnnotationsDiagnostic(
						diagnostics,
						FindAttribute(attributes, executionContext.RegularExpressionAttribute),
						string.Format(
							CultureInfo.InvariantCulture,
							"RegularExpressionAttribute can only be applied to string properties, but '{0}' is '{1}'.",
							property.Name,
							propertyType.ToDisplayString()
						)
					);
				}
				else
				{
					executionContext.Writer.WriteLine(
						$"static readonly global::System.Text.RegularExpressions.Regex {GetRegexFieldName(property.Name)} = new({Quote(regexAttribute.Pattern!)}, global::System.Text.RegularExpressions.RegexOptions.CultureInvariant);"
					);
				}
			}

			var rangeAttribute = RangeAttributeData.FromAttributeData(executionContext, attributes);
			if (
				rangeAttribute.Exists
				&& TryBuildRangeBoundaryExpressions(
					propertyType,
					rangeAttribute,
					out var minimumExpression,
					out var maximumExpression
				)
			)
			{
				var fqTypeName = GetFullyQualifiedTypeName(propertyType);
				executionContext.Writer.WriteLine(
					$"static readonly {fqTypeName} {GetRangeMinimumFieldName(property.Name)} = {minimumExpression};"
				);
				executionContext.Writer.WriteLine(
					$"static readonly {fqTypeName} {GetRangeMaximumFieldName(property.Name)} = {maximumExpression};"
				);
			}
		}

		executionContext.Writer.WriteLine();
	}

	static void GenerateValidationHelpers(ExecutionContext executionContext)
	{
		executionContext.Writer.WriteLine(
			$"static void AddError(ref {typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>? errors, {TypeHelpers.ValidationError.Global()} error)"
		);
		using (executionContext.Writer.Block())
		{
			executionContext.Writer.WriteLine(
				$"(errors ??= new {typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>()).Add(error);"
			);
		}

		executionContext.Writer.WriteLine();
		executionContext.Writer.WriteLine(
			"static string FormatCount(int count, string singularNoun, string pluralNoun)"
		);
		using (executionContext.Writer.Block())
		{
			executionContext.Writer.WriteLine("return count == 1 ? $\"1 {singularNoun}\" : $\"{count} {pluralNoun}\";");
		}

		executionContext.Writer.WriteLine();
	}

	static string GetPathFieldName(string propertyName) => $"Path_{propertyName}";

	static string GetLocalIdentifier(string propertyName, string suffix) =>
		string.IsNullOrEmpty(propertyName)
			? suffix
			: char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1) + suffix;

	static string Quote(string value) => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

	static void GenerateParseMethod(ExecutionContext executionContext, string fullTypeName)
	{
		executionContext.Writer.WriteLine("/// <summary>");
		executionContext.Writer.WriteLine(
			"/// Validates and returns the value, throwing an exception if validation fails."
		);
		executionContext.Writer.WriteLine("/// </summary>");
		executionContext.Writer.WriteLine($"public static {fullTypeName} Parse({fullTypeName} value)");
		using (executionContext.Writer.Block())
		{
			executionContext.Writer.WriteLine("return Validate(value).GetValueOrThrow();");
		}
	}

	static void GenerateCompositionMethods(StringBuilder sb, INamedTypeSymbol classSymbol, string fullTypeName)
	{
		sb.AppendLine();
		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Creates a schema that requires both this and another schema to pass.");
		sb.AppendLine("    /// Equivalent to Zod's .and() method.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> And({fullTypeName} value, global::System.Func<{fullTypeName}, bool> additionalValidation, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (!result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (!additionalValidation(value))");
		sb.AppendLine("        {");
		sb.AppendLine($"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(");
		sb.AppendLine($"                {TypeHelpers.ValidationError.Global()}.Create(");
		sb.AppendLine("                    \"validation_failed\",");
		sb.AppendLine($"                    message ?? \"Additional validation failed for {classSymbol.Name}\",");
		sb.AppendLine("                    EmptyPath");
		sb.AppendLine("                )");
		sb.AppendLine("            );");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        return result;");
		sb.AppendLine("    }");
		sb.AppendLine();

		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Creates a schema that requires either this or another validation to pass.");
		sb.AppendLine("    /// Equivalent to Zod's .or() method.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static ${TypeHelpers.ValidationResult.Global()}<{fullTypeName}> Or({fullTypeName} value, global::System.Func<{fullTypeName}, bool> alternativeValidation, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (alternativeValidation(value))");
		sb.AppendLine("        {");
		sb.AppendLine($"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Success(value);");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine($"        return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(");
		sb.AppendLine($"            {TypeHelpers.ValidationError.Global()}.Create(");
		sb.AppendLine("                \"validation_failed\",");
		sb.AppendLine($"                message ?? \"Neither validation passed for {classSymbol.Name}\",");
		sb.AppendLine("                EmptyPath");
		sb.AppendLine("            )");
		sb.AppendLine("        );");
		sb.AppendLine("    }");
		sb.AppendLine();

		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Adds a custom refinement to the validation.");
		sb.AppendLine("    /// Equivalent to Zod's .refine() method.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> Refine({fullTypeName} value, global:System.Func<{fullTypeName}, bool> refinement, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (!result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (!refinement(value))");
		sb.AppendLine("        {");
		sb.AppendLine($"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(");
		sb.AppendLine($"            {TypeHelpers.ValidationError.Global()}.Create(");
		sb.AppendLine("                \"validation_failed\",");
		sb.AppendLine($"                message ?? \"Refinement validation failed for {classSymbol.Name}\",");
		sb.AppendLine("                EmptyPath");
		sb.AppendLine("            )");
		sb.AppendLine("            );");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        return result;");
		sb.AppendLine("    }");
	}
}
