<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<!-- Stops auto TUnit/ Bogus etc being included -->
		<IsTestProject>false</IsTestProject>
		<RootNamespace>ZodSharp</RootNamespace>
		<NoWarn>$(NoWarn);CA1303;CA1707;CA1822;CA1515;</NoWarn>
		<OutputType>Exe</OutputType>
		<AssemblyName>Purview.ZodSharp.PerformanceBenchmark</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ZodSharp\ZodSharp.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" />
		<PackageReference Include="Newtonsoft.Json" />
	</ItemGroup>
</Project>
