<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AutoIncludeUsings>false</AutoIncludeUsings>
		<RootNamespace>ZodSharp</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>Purview.ZodSharp.NewtonsoftJson</AssemblyName>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<PackageId>Purview.ZodSharp.NewtonsoftJson</PackageId>
		<Description>A high-performance C# port of Zod schema validation library. Features zero-allocation validation, struct-based rules, fluent API, and source generator support for maximum performance.</Description>
		<PackageTags>zod;validation;schema;json</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ZodSharp\ZodSharp.csproj" />
	</ItemGroup>
</Project>
