<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks></TargetFrameworks>
		<TargetFramework>net10.0</TargetFramework>
		<IsTestProject>false</IsTestProject>
		<IsPackable>false</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DisableNamespacePrefixCheck>true</DisableNamespacePrefixCheck>
		<NoWarn>$(NoWarn);IDE0005;IDE0130;CA1859;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
	</ItemGroup>
</Project>
