<Project>
	<PropertyGroup>
		<ZodSharpNetTargetFrameworks>net8.0;net9.0;net10.0</ZodSharpNetTargetFrameworks>
		<TargetFrameworks>$(ZodSharpNetTargetFrameworks)</TargetFrameworks>
		<NamespacePrefix>ZodSharp</NamespacePrefix>
		<!-- Set project-by-project -->
		<IsPackable>false</IsPackable>
		<ExcludePurviewTelemetry>true</ExcludePurviewTelemetry>
		<RepositoryUrl>https://github.com/purview-dev/zodsharp</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);CA1031;CA1510;</NoWarn>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.props" />

	<PropertyGroup Condition="'$(IsTestProject)' == 'true' OR '$(OutputType)' == 'Exe'">
		<TargetFramework></TargetFramework>
		<TargetFrameworks>$(ZodSharpNetTargetFrameworks)</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Label="Purview site URL metadata">
		<PurviewHomepage>https://purview.dev/</PurviewHomepage>
		<PurviewProjectUrl>$(PurviewHomepage)projects/zodsharp/</PurviewProjectUrl>
		<PurviewDocsUrl>$(PurviewHomepage)docs/zodsharp/</PurviewDocsUrl>
	</PropertyGroup>

	<PropertyGroup Label="NuGet package metadata" Condition="'$(IsPackable)' == 'true'">
		<Authors>ZodSharp Contributors;Purview-Dev Contributors</Authors>
		<Company>Purview.dev</Company>
		<PackageProjectUrl>$(PurviewProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PackageIcon>purview-logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGet package assets" Condition="'$(IsPackable)' == 'true'">
		<None Include="$(MSBuildThisFileDirectory)/../assets/images/purview-logo.png" Link="Sdk/purview-logo.png" />
	</ItemGroup>
</Project>
