<Project>
	<PropertyGroup>
		<ZodSharpNetTargetFrameworks>net8.0;net9.0;net10.0</ZodSharpNetTargetFrameworks>
		<TargetFrameworks>$(ZodSharpNetTargetFrameworks)</TargetFrameworks>
		<NamespacePrefix>ZodSharp</NamespacePrefix>
		<!-- Set project-by-project -->
		<IsPackable>false</IsPackable>
		<ExcludePurviewTelemetry>true</ExcludePurviewTelemetry>
		<RepositoryUrl>https://github.com/purview-dev/zodsharp</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);CA1031;CA1510;</NoWarn>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.props" />

	<PropertyGroup Condition="'$(IsTestProject)' == 'true' OR '$(OutputType)' == 'Exe'">
		<TargetFramework></TargetFramework>
		<TargetFrameworks>$(ZodSharpNetTargetFrameworks)</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsPackable)' == 'true'">
		<Authors>ZodSharp Contributors;Purview-Dev Contributors</Authors>
		<PackageProjectUrl>https://github.com/purview-dev/zodsharp</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
</Project>
