using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZodSharp.SourceGenerators.Helpers;
using ZodSharp.SourceGenerators.Helpers.Models;
using ExecutionContext = ZodSharp.SourceGenerators.Helpers.Models.ExecutionContext;

namespace ZodSharp.SourceGenerators;

partial class ZodSchemaGenerator
{
	static void Execute(
		TargetSymbolDescriptor targetDescriptor,
		ExecutionContext executionContext,
		SourceProductionContext context
	)
	{
		try
		{
			using (executionContext.Writer.Begin())
			{
				var source = GenerateSchemaClass(targetDescriptor.Symbol, executionContext);
				var fileName = $"{targetDescriptor.Symbol.Name}Schema.g.cs";
				context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
			}
		}
		catch (Exception ex)
		{
			// Report diagnostic if generation fails
			var diagnostic = Diagnostic.Create(
				GeneratorDiagnostics.UnhandledException,
				targetDescriptor.Declaration.GetLocation(),
				targetDescriptor.Symbol.Name,
				ex.Message
			);

			ReportDiagnostics(context, diagnostic, executionContext);
		}
	}

	static string GenerateSchemaClass(INamedTypeSymbol classSymbol, ExecutionContext executionContext)
	{
		var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
		var className = classSymbol.Name;
		var schemaName = $"{className}Schema";
		var fullTypeName = classSymbol.ToDisplayString();
		var modifier = TypeHelpers.GetLimitedAccessibilityKeyword(classSymbol);

		executionContext.Logger?.Info(
			$"Generating schema {schemaName} ({modifier}) for {className} in namespace {namespaceName}"
		);

		// Estimate capacity based on number of properties
		var propertyCount = classSymbol
			.GetMembers()
			.OfType<IPropertySymbol>()
			.Count(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

		executionContext.Logger?.Info($"Property count for {className}: {propertyCount}", 1);

		executionContext.Writer.WriteLine("// <auto-generated />");
		executionContext.Writer.WriteLine();
		executionContext.Writer.WriteLine("using System;");
		executionContext.Writer.WriteLine("using System.Collections.Generic;");
		executionContext.Writer.WriteLine("using System.Collections.Immutable;");

		executionContext.Writer.WriteLine("using ZodSharp.Core;");
		executionContext.Writer.WriteLine();

		executionContext.Writer.WriteLine($"namespace {namespaceName};");
		executionContext.Writer.WriteLine();
		executionContext.Writer.WriteLine("#nullable enable");
		executionContext.Writer.WriteLine();
		executionContext.Writer.WriteLine("/// <summary>");
		executionContext.Writer.WriteLine($"/// Auto-generated schema validator for {className}.");
		executionContext.Writer.WriteLine(
			"/// This class is generated at compile time for zero-allocation validation."
		);
		executionContext.Writer.WriteLine("/// </summary>");
		executionContext.Writer.WriteLine("{{CodeGen}}");

		using (executionContext.Writer.Block($"{modifier} static partial class {schemaName}"))
		{
			executionContext.Writer.WriteLine(
				"static readonly string[] EmptyPath = global::System.Array.Empty<string>();"
			);
			executionContext.Writer.WriteLine();

			GenerateValidateMethod(executionContext, classSymbol, fullTypeName);
			GenerateParseMethod(executionContext, fullTypeName);
		}

		return CodeGenHelpers.ProcessGeneratedCode(executionContext.Writer.ToString());
	}

	static void GenerateValidateMethod(
		ExecutionContext executionContext,
		INamedTypeSymbol classSymbol,
		string fullTypeName
	)
	{
		var writer = executionContext.Writer;
		writer.WriteLine("/// <summary>");
		writer.WriteLine("/// Validates an instance of the target type.");
		writer.WriteLine("/// </summary>");
		writer.WriteLine(
			$"public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> Validate({fullTypeName} value)"
		);

		using (writer.Block())
		{
			if (TypeHelpers.CanBeNull(classSymbol))
			{
				using (writer.Block("if (value == null)"))
				{
					using (
						writer.Block(
							$"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure",
							seperator: "(",
							closingSeperator: ");"
						)
					)
					{
						using (writer.Block($"new {TypeHelpers.ValidationError.Global()}", seperator: "("))
						{
							writer.WriteIndent().Quote("invalid_type").Write(",").NewLine();
							writer.WriteIndent().Quote("Value cannot be null").Write(",").NewLine();
							writer.WriteIndent().Write("EmptyPath").NewLine();
						}
					}
				}

				writer.NewLine();
			}

			writer.WriteLine(
				$"var errors = new {typeof(List<>).Namespace.Global()}.List<{TypeHelpers.ValidationError.Global()}>();"
			);

			var properties = classSymbol
				.GetMembers()
				.OfType<IPropertySymbol>()
				.Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
				.ToList();

			foreach (var property in properties)
				GeneratePropertyValidation(executionContext, property);

			using (writer.Block("if (errors.Count > 0)"))
			{
				writer.WriteLine($"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(errors);");
			}

			writer
				.WriteLine()
				.WriteLine($"return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Success(value);");
		}
	}

	static void GeneratePropertyValidation(ExecutionContext executionContext, IPropertySymbol property)
	{
		var propertyName = property.Name;
		var propertyType = property.Type;
		var canBeNull = TypeHelpers.CanBeNull(propertyType);

		var attributes = property.GetAttributes();
		var requiredAttrib = RequiredAttributeData.FromAttributeData(executionContext, attributes);

		IDisposable? block = null;
		if (canBeNull && requiredAttrib.Exists)
		{
			var isStringAndAllowEmptyStrings =
				propertyType.SpecialType == SpecialType.System_String && requiredAttrib.AllowEmptyStrings;
			var localErrorMessage =
				(isStringAndAllowEmptyStrings)
					? "Field '{0}' is required and cannot be null or empty"
					: "Required field '{0}' is null";

			var errorMessage = string.Format(
				CultureInfo.InvariantCulture,
				(requiredAttrib.ErrorMessage ?? localErrorMessage),
				propertyName
			);

			var comparision = isStringAndAllowEmptyStrings
				? $"string.IsNullOrEmpty(value.{propertyName})"
				: $"value.{propertyName} == null";

			executionContext.Writer.WriteRule(propertyName, comparision, "missing_field", errorMessage);

			block = executionContext.Writer.Block(("else"));
		}
		else if (canBeNull)
		{
			block = executionContext.Writer.Block(($"if (value.{propertyName} != null)"));
		}

		GenerateTypeSpecificValidations(executionContext, propertyType, attributes, propertyName);

		block?.Dispose();

		executionContext.Writer.WriteLine();
	}

	static void GenerateTypeSpecificValidations(
		ExecutionContext executionContext,
		ITypeSymbol propertyType,
		ImmutableArray<AttributeData> attributes,
		string propertyName
	)
	{
		if (propertyType.SpecialType == SpecialType.System_String)
		{
			GenerateStringValidations(executionContext, propertyName, attributes);
		}
		else if (TypeHelpers.IsNumericType(propertyType))
		{
			GenerateNumericValidations(executionContext, propertyName, attributes);
		}
		else if (
			propertyType is IArrayTypeSymbol
			|| (
				propertyType is INamedTypeSymbol namedType
				&& namedType.IsGenericType
				&& namedType.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T
			)
		)
		{
			GenerateCollectionValidations(executionContext, propertyType, propertyName, attributes);
		}
	}

	static void GenerateParseMethod(ExecutionContext executionContext, string fullTypeName)
	{
		executionContext.Writer.WriteLine("/// <summary>");
		executionContext.Writer.WriteLine(
			"/// Validates and returns the value, throwing an exception if validation fails."
		);
		executionContext.Writer.WriteLine("/// </summary>");
		executionContext.Writer.WriteLine($"public static {fullTypeName} Parse({fullTypeName} value)");
		using (executionContext.Writer.Block())
		{
			executionContext.Writer.WriteLine("return Validate(value).GetValueOrThrow();");
		}
	}

	static void GenerateCompositionMethods(StringBuilder sb, INamedTypeSymbol classSymbol, string fullTypeName)
	{
		sb.AppendLine();
		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Creates a schema that requires both this and another schema to pass.");
		sb.AppendLine("    /// Equivalent to Zod's .and() method.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> And({fullTypeName} value, global::System.Func<{fullTypeName}, bool> additionalValidation, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (!result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (!additionalValidation(value))");
		sb.AppendLine("        {");
		sb.AppendLine($"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(");
		sb.AppendLine($"                new {TypeHelpers.ValidationError.Global()}(");
		sb.AppendLine("                    \"validation_failed\",");
		sb.AppendLine($"                    message ?? \"Additional validation failed for {classSymbol.Name}\",");
		sb.AppendLine("                    EmptyPath");
		sb.AppendLine("                )");
		sb.AppendLine("            );");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        return result;");
		sb.AppendLine("    }");
		sb.AppendLine();

		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Creates a schema that requires either this or another validation to pass.");
		sb.AppendLine("    /// Equivalent to Zod's .or() method.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static ${TypeHelpers.ValidationResult.Global()}<{fullTypeName}> Or({fullTypeName} value, global::System.Func<{fullTypeName}, bool> alternativeValidation, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (alternativeValidation(value))");
		sb.AppendLine("        {");
		sb.AppendLine($"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Success(value);");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine($"        return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(");
		sb.AppendLine($"            new {TypeHelpers.ValidationError.Global()}(");
		sb.AppendLine("                \"validation_failed\",");
		sb.AppendLine($"                message ?? \"Neither validation passed for {classSymbol.Name}\",");
		sb.AppendLine("                EmptyPath");
		sb.AppendLine("            )");
		sb.AppendLine("        );");
		sb.AppendLine("    }");
		sb.AppendLine();

		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Adds a custom refinement to the validation.");
		sb.AppendLine("    /// Equivalent to Zod's .refine() method.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine(
			$"    public static {TypeHelpers.ValidationResult.Global()}<{fullTypeName}> Refine({fullTypeName} value, global:System.Func<{fullTypeName}, bool> refinement, string? message = null)"
		);
		sb.AppendLine("    {");
		sb.AppendLine("        var result = Validate(value);");
		sb.AppendLine("        if (!result.IsSuccess)");
		sb.AppendLine("        {");
		sb.AppendLine("            return result;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        if (!refinement(value))");
		sb.AppendLine("        {");
		sb.AppendLine($"            return {TypeHelpers.ValidationResult.Global()}<{fullTypeName}>.Failure(");
		sb.AppendLine($"            new {TypeHelpers.ValidationError.Global()}(");
		sb.AppendLine("                \"validation_failed\",");
		sb.AppendLine($"                message ?? \"Refinement validation failed for {classSymbol.Name}\",");
		sb.AppendLine("                EmptyPath");
		sb.AppendLine("            )");
		sb.AppendLine("            );");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        return result;");
		sb.AppendLine("    }");
	}
}
